export const typeGroups : any[] = [
{ key: "Bulbasaur_Durin", pokemon: [ "Bulbasaur", "Ivysaur", "Venusaur",  ], default: "Venusaur", berry: "Durin",  },
{ key: "Charmander_Leppa", pokemon: [ "Charmander", "Charmeleon", "Charizard",  ], default: "Charizard", berry: "Leppa",  },
{ key: "Squirtle_Oran", pokemon: [ "Squirtle", "Wartortle", "Blastoise",  ], default: "Blastoise", berry: "Oran",  },
{ key: "Caterpie_Lum", pokemon: [ "Caterpie", "Metapod", "Butterfree",  ], default: "Butterfree", berry: "Lum",  },
{ key: "Rattata_Persim", pokemon: [ "Rattata", "Raticate",  ], default: "Raticate", berry: "Persim",  },
{ key: "Ekans_Chesto", pokemon: [ "Ekans", "Arbok",  ], default: "Arbok", berry: "Chesto",  },
{ key: "Pichu_Grepa", pokemon: [ "Pichu", "Pikachu", "Raichu",  ], default: "Raichu", berry: "Grepa",  },
{ key: "Cleffa_Pecha", pokemon: [ "Cleffa", "Clefairy", "Clefable",  ], default: "Clefable", berry: "Pecha",  },
{ key: "Vulpix_Leppa", pokemon: [ "Vulpix", "Ninetails",  ], default: "Ninetails", berry: "Leppa",  },
{ key: "Igglybuff_Pecha", pokemon: [ "Igglybuff", "Jigglypuff", "Wigglytuff",  ], default: "Wigglytuff", berry: "Pecha",  },
{ key: "Diglett_Figy", pokemon: [ "Diglett", "Dugtrio",  ], default: "Dugtrio", berry: "Figy",  },
{ key: "Meowth_Persim", pokemon: [ "Meowth", "Persian",  ], default: "Persian", berry: "Persim",  },
{ key: "Psyduck_Oran", pokemon: [ "Psyduck", "Golduck",  ], default: "Golduck", berry: "Oran",  },
{ key: "Mankey_Cheri", pokemon: [ "Mankey", "Primeape",  ], default: "Primeape", berry: "Cheri",  },
{ key: "Growlithe_Leppa", pokemon: [ "Growlithe", "Arcanine",  ], default: "Arcanine", berry: "Leppa",  },
{ key: "Bellsprout_Durin", pokemon: [ "Bellsprout", "Weepinbell", "Victreebel",  ], default: "Victreebel", berry: "Durin",  },
{ key: "Geodude_Sitrus", pokemon: [ "Geodude", "Graveler", "Golem",  ], default: "Golem", berry: "Sitrus",  },
{ key: "Slowpoke_Oran", pokemon: [ "Slowpoke", "Slowbro", "Slowking",  ], default: "Slowpoke", berry: "Oran",  },
{ key: "Magnemite_Belue", pokemon: [ "Magnemite", "Magneton", "Magnezone",  ], default: "Magnezone", berry: "Belue",  },
{ key: "Doduo_Pamtre", pokemon: [ "Doduo", "Dodrio",  ], default: "Dodrio", berry: "Pamtre",  },
{ key: "Gastly_Bluk", pokemon: [ "Gastly", "Haunter", "Gengar",  ], default: "Gengar", berry: "Bluk",  },
{ key: "Onix_Sitrus", pokemon: [ "Onix",  ], default: "Onix", berry: "Sitrus",  },
{ key: "Onix_Belue", pokemon: [ "Steelix",  ], default: "Steelix", berry: "Belue",  },
{ key: "Cubone_Figy", pokemon: [ "Cubone", "Marowak",  ], default: "Marowak", berry: "Figy",  },
{ key: "Kangaskhan_Persim", pokemon: [ "Kangaskhan",  ], default: "Kangaskhan", berry: "Persim",  },
{ key: "Mime Jr._Mago", pokemon: [ "Mime Jr.", "Mr. Mime",  ], default: "Mr. Mime", berry: "Mago",  },
{ key: "Pinsir_Lum", pokemon: [ "Pinsir",  ], default: "Pinsir", berry: "Lum",  },
{ key: "Ditto_Persim", pokemon: [ "Ditto",  ], default: "Ditto", berry: "Persim",  },
{ key: "Eevee_Persim", pokemon: [ "Eevee",  ], default: "Eevee", berry: "Persim",  },
{ key: "Eevee_Oran", pokemon: [ "Vaporeon",  ], default: "Vaporeon", berry: "Oran",  },
{ key: "Eevee_Grepa", pokemon: [ "Jolteon",  ], default: "Jolteon", berry: "Grepa",  },
{ key: "Eevee_Leppa", pokemon: [ "Flareon",  ], default: "Flareon", berry: "Leppa",  },
{ key: "Eevee_Mago", pokemon: [ "Espeon",  ], default: "Espeon", berry: "Mago",  },
{ key: "Eevee_Wiki", pokemon: [ "Umbreon",  ], default: "Umbreon", berry: "Wiki",  },
{ key: "Eevee_Durin", pokemon: [ "Leafeon",  ], default: "Leafeon", berry: "Durin",  },
{ key: "Eevee_Rawst", pokemon: [ "Glaceon",  ], default: "Glaceon", berry: "Rawst",  },
{ key: "Eevee_Pecha", pokemon: [ "Sylveon",  ], default: "Sylveon", berry: "Pecha",  },
{ key: "Dratini_Yache", pokemon: [ "Dratini", "Dragonair", "Dragonite",  ], default: "Dragonite", berry: "Yache",  },
{ key: "Chikorita_Durin", pokemon: [ "Chikorita", "Bayleef", "Meganium",  ], default: "Meganium", berry: "Durin",  },
{ key: "Cyndaquil_Leppa", pokemon: [ "Cyndaquil", "Quilava", "Typhlosion",  ], default: "Typhlosion", berry: "Leppa",  },
{ key: "Totodile_Oran", pokemon: [ "Totodile", "Croconaw", "Feraligatr",  ], default: "Feraligatr", berry: "Oran",  },
{ key: "Togepi_Pecha", pokemon: [ "Togepi", "Togetic", "Togekiss",  ], default: "Togekiss", berry: "Pecha",  },
{ key: "Mareep_Grepa", pokemon: [ "Mareep", "Flaaffy", "Ampharos",  ], default: "Ampharos", berry: "Grepa",  },
{ key: "Bonsly_Sitrus", pokemon: [ "Bonsly", "Sudowoodo",  ], default: "Sudowoodo", berry: "Sitrus",  },
{ key: "Wooper_Oran", pokemon: [ "Wooper", "Quagsire",  ], default: "Quagsire", berry: "Oran",  },
{ key: "Wynaut_Mago", pokemon: [ "Wynaut", "Wobbuffet",  ], default: "Wobbuffet", berry: "Mago",  },
{ key: "Heracross_Lum", pokemon: [ "Heracross",  ], default: "Heracross", berry: "Lum",  },
{ key: "Delibird_Pamtre", pokemon: [ "Delibird",  ], default: "Delibird", berry: "Pamtre",  },
{ key: "Houndour_Wiki", pokemon: [ "Houndour", "Houndoom",  ], default: "Houndoom", berry: "Wiki",  },
{ key: "Raiku_Grepa", pokemon: [ "Raiku",  ], default: "Raiku", berry: "Grepa",  },
{ key: "Entei_Leppa", pokemon: [ "Entei",  ], default: "Entei", berry: "Leppa",  },
{ key: "Suicune_Oran", pokemon: [ "Suicune",  ], default: "Suicune", berry: "Oran",  },
{ key: "Larvitar_Sitrus", pokemon: [ "Larvitar", "Pupitar",  ], default: "Larvitar", berry: "Sitrus",  },
{ key: "Larvitar_Wiki", pokemon: [ "Tyranitar",  ], default: "Tyranitar", berry: "Wiki",  },
{ key: "Ralts_Mago", pokemon: [ "Ralts", "Kirlia", "Gardevoir",  ], default: "Gardevoir", berry: "Mago",  },
{ key: "Ralts_Cheri", pokemon: [ "Gallade",  ], default: "Gallade", berry: "Cheri",  },
{ key: "Slakoth_Persim", pokemon: [ "Slakoth", "Vigoroth", "Slaking",  ], default: "Slaking", berry: "Persim",  },
{ key: "Aron_Belue", pokemon: [ "Aron", "Lairon", "Aggron",  ], default: "Aggron", berry: "Belue",  },
{ key: "Sableye_Wiki", pokemon: [ "Sableye",  ], default: "Sableye", berry: "Wiki",  },
{ key: "Gulpin_Chesto", pokemon: [ "Gulpin", "Swalot",  ], default: "Swalot", berry: "Chesto",  },
{ key: "Swablu_Pamtre", pokemon: [ "Swablu",  ], default: "Swablu", berry: "Pamtre",  },
{ key: "Swablu_Yache", pokemon: [ "Altaria",  ], default: "Altaria", berry: "Yache",  },
{ key: "Shuppet_Bluk", pokemon: [ "Shuppet", "Banette",  ], default: "Banette", berry: "Bluk",  },
{ key: "Absol_Wiki", pokemon: [ "Absol",  ], default: "Absol", berry: "Wiki",  },
{ key: "Spheal_Rawst", pokemon: [ "Spheal", "Sealeo", "Walrein",  ], default: "Walrein", berry: "Rawst",  },
{ key: "Shinx_Grepa", pokemon: [ "Shinx", "Luxio", "Luxray",  ], default: "Luxray", berry: "Grepa",  },
{ key: "Drifloon_Bluk", pokemon: [ "Drifloon", "Drifblim",  ], default: "Drifblim", berry: "Bluk",  },
{ key: "Riolu_Cheri", pokemon: [ "Riolu", "Lucario",  ], default: "Lucario", berry: "Cheri",  },
{ key: "Croagunk_Chesto", pokemon: [ "Croagunk", "Toxicroak",  ], default: "Toxicroak", berry: "Chesto",  },
{ key: "Snover_Rawst", pokemon: [ "Snover", "Abomasnow",  ], default: "Abomasnow", berry: "Rawst",  },
{ key: "Dedenne_Grepa", pokemon: [ "Dedenne",  ], default: "Dedenne", berry: "Grepa",  },
{ key: "Grubbin_Lum", pokemon: [ "Grubbin", "Charjabug", "Vikabolt",  ], default: "Vikabolt", berry: "Lum",  },
{ key: "Stufful_Cheri", pokemon: [ "Stufful", "Bewear",  ], default: "Bewear", berry: "Cheri",  },
{ key: "Comfey_Pecha", pokemon: [ "Comfey",  ], default: "Comfey", berry: "Pecha",  },
{ key: "Mimikyu_Bluk", pokemon: [ "Mimikyu",  ], default: "Mimikyu", berry: "Bluk",  },
{ key: "Cramorant_Pamtre", pokemon: [ "Cramorant",  ], default: "Cramorant", berry: "Pamtre",  },
{ key: "Sprigatito_Durin", pokemon: [ "Sprigatito", "Floragato",  ], default: "Sprigatito", berry: "Durin",  },
{ key: "Sprigatito_Wiki", pokemon: [ "Meowscarada",  ], default: "Meowscarada", berry: "Wiki",  },
{ key: "Fuecoco_Leppa", pokemon: [ "Fuecoco", "Crocalor",  ], default: "Fuecoco", berry: "Leppa",  },
{ key: "Fuecoco_Bluk", pokemon: [ "Skeledirge",  ], default: "Skeledirge", berry: "Bluk",  },
{ key: "Quaxly_Oran", pokemon: [ "Quaxly", "Quaxwell",  ], default: "Quaxly", berry: "",  },
{ key: "Quaxly_Cheri", pokemon: [ "Quaquaval",  ], default: "Quaquaval", berry: "",  },
]