
export type Pokemon = {
  id: string,
  name: string,
  portraitUri: string,
  berry: string,
  ingredient_1: string,
  ingredient_2: string,
  ingredient_3: string,
}

export const pokedex : Pokemon[] = [
  { id: '1', name: 'Bulbasaur', portraitUri: "./portraits/001.png", berry: 'Durin', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Potato',  },
  { id: '2', name: 'Ivysaur', portraitUri: "./portraits/002.png", berry: 'Durin', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Potato',  },
  { id: '3', name: 'Venusaur', portraitUri: "./portraits/003.png", berry: 'Durin', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Potato',  },
  { id: '4', name: 'Charmander', portraitUri: "./portraits/004.png", berry: 'Leppa', ingredient_1: 'Sausage', ingredient_2: 'Ginger', ingredient_3: 'Herb',  },
  { id: '5', name: 'Charmeleon', portraitUri: "./portraits/005.png", berry: 'Leppa', ingredient_1: 'Sausage', ingredient_2: 'Ginger', ingredient_3: 'Herb',  },
  { id: '6', name: 'Charizard', portraitUri: "./portraits/006.png", berry: 'Leppa', ingredient_1: 'Sausage', ingredient_2: 'Ginger', ingredient_3: 'Herb',  },
  { id: '7', name: 'Squirtle', portraitUri: "./portraits/007.png", berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '8', name: 'Wartortle', portraitUri: "./portraits/008.png", berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '9', name: 'Blastoise', portraitUri: "./portraits/009.png", berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '10', name: 'Caterpie', portraitUri: "./portraits/010.png", berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Soybeans',  },
  { id: '11', name: 'Metapod', portraitUri: "./portraits/011.png", berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Soybeans',  },
  { id: '12', name: 'Butterfree', portraitUri: "./portraits/012.png", berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Soybeans',  },
  { id: '13', name: 'Rattata', portraitUri: "./portraits/019.png", berry: 'Persim', ingredient_1: 'Apple', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '14', name: 'Raticate', portraitUri: "./portraits/020.png", berry: 'Persim', ingredient_1: 'Apple', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '15', name: 'Ekans', portraitUri: "./portraits/023.png", berry: 'Chesto', ingredient_1: 'Sausage', ingredient_2: 'Egg', ingredient_3: 'Herb',  },
  { id: '16', name: 'Arbok', portraitUri: "./portraits/024.png", berry: 'Chesto', ingredient_1: 'Sausage', ingredient_2: 'Egg', ingredient_3: 'Herb',  },
  { id: '17', name: 'Pichu', portraitUri: "./portraits/172.png", berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Ginger', ingredient_3: 'Egg',  },
  { id: '18', name: 'Pikachu', portraitUri: "./portraits/025.png", berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Ginger', ingredient_3: 'Egg',  },
  { id: '19', name: 'Raichu', portraitUri: "./portraits/026.png", berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Ginger', ingredient_3: 'Egg',  },
  { id: '20', name: 'Cleffa', portraitUri: "./portraits/173.png", berry: 'Pecha', ingredient_1: 'Apple', ingredient_2: 'Honey', ingredient_3: 'Soybeans',  },
  { id: '21', name: 'Clefairy', portraitUri: "./portraits/035.png", berry: 'Pecha', ingredient_1: 'Apple', ingredient_2: 'Honey', ingredient_3: 'Soybeans',  },
  { id: '22', name: 'Clefable', portraitUri: "./portraits/036.png", berry: 'Pecha', ingredient_1: 'Apple', ingredient_2: 'Honey', ingredient_3: 'Soybeans',  },
  { id: '23', name: 'Vulpix', portraitUri: "./portraits/037.png", berry: 'Leppa', ingredient_1: 'Soybeans', ingredient_2: 'Corn', ingredient_3: 'Potato',  },
  { id: '24', name: 'Ninetails', portraitUri: "./portraits/038.png", berry: 'Leppa', ingredient_1: 'Soybeans', ingredient_2: 'Corn', ingredient_3: 'Potato',  },
  { id: '25', name: 'Igglybuff', portraitUri: "./portraits/174.png", berry: 'Pecha', ingredient_1: 'Honey', ingredient_2: 'Oil', ingredient_3: 'Cacao',  },
  { id: '26', name: 'Jigglypuff', portraitUri: "./portraits/039.png", berry: 'Pecha', ingredient_1: 'Honey', ingredient_2: 'Oil', ingredient_3: 'Cacao',  },
  { id: '27', name: 'Wigglytuff', portraitUri: "./portraits/040.png", berry: 'Pecha', ingredient_1: 'Honey', ingredient_2: 'Oil', ingredient_3: 'Cacao',  },
  { id: '28', name: 'Diglett', portraitUri: "./portraits/050.png", berry: 'Figy', ingredient_1: 'Tomato', ingredient_2: 'Leek', ingredient_3: 'Soybeans',  },
  { id: '29', name: 'Dugtrio', portraitUri: "./portraits/051.png", berry: 'Figy', ingredient_1: 'Tomato', ingredient_2: 'Leek', ingredient_3: 'Soybeans',  },
  { id: '30', name: 'Meowth', portraitUri: "./portraits/052.png", berry: 'Persim', ingredient_1: 'Milk', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '31', name: 'Persian', portraitUri: "./portraits/053.png", berry: 'Persim', ingredient_1: 'Milk', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '32', name: 'Psyduck', portraitUri: "./portraits/054.png", berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Apple', ingredient_3: 'Sausage',  },
  { id: '33', name: 'Golduck', portraitUri: "./portraits/055.png", berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Apple', ingredient_3: 'Sausage',  },
  { id: '34', name: 'Mankey', portraitUri: "./portraits/056.png", berry: 'Cheri', ingredient_1: 'Sausage', ingredient_2: 'Mushroom', ingredient_3: 'Honey',  },
  { id: '35', name: 'Primeape', portraitUri: "./portraits/057.png", berry: 'Cheri', ingredient_1: 'Sausage', ingredient_2: 'Mushroom', ingredient_3: 'Honey',  },
  { id: '36', name: 'Growlithe', portraitUri: "./portraits/058.png", berry: 'Leppa', ingredient_1: 'Herb', ingredient_2: 'Sausage', ingredient_3: 'Milk',  },
  { id: '37', name: 'Arcanine', portraitUri: "./portraits/059.png", berry: 'Leppa', ingredient_1: 'Herb', ingredient_2: 'Sausage', ingredient_3: 'Milk',  },
  { id: '38', name: 'Bellsprout', portraitUri: "./portraits/069.png", berry: 'Durin', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '39', name: 'Weepinbell', portraitUri: "./portraits/070.png", berry: 'Durin', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '40', name: 'Victreebel', portraitUri: "./portraits/071.png", berry: 'Durin', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '41', name: 'Geodude', portraitUri: "./portraits/074.png", berry: 'Sitrus', ingredient_1: 'Soybeans', ingredient_2: 'Potato', ingredient_3: 'Mushroom',  },
  { id: '42', name: 'Graveler', portraitUri: "./portraits/075.png", berry: 'Sitrus', ingredient_1: 'Soybeans', ingredient_2: 'Potato', ingredient_3: 'Mushroom',  },
  { id: '43', name: 'Golem', portraitUri: "./portraits/076.png", berry: 'Sitrus', ingredient_1: 'Soybeans', ingredient_2: 'Potato', ingredient_3: 'Mushroom',  },
  { id: '44', name: 'Slowpoke', portraitUri: "./portraits/079.png", berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Tail', ingredient_3: 'Tomato',  },
  { id: '45', name: 'Slowbro', portraitUri: "./portraits/080.png", berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Tail', ingredient_3: 'Tomato',  },
  { id: '46', name: 'Slowking', portraitUri: "./portraits/199.png", berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Tail', ingredient_3: 'Tomato',  },
  { id: '47', name: 'Magnemite', portraitUri: "./portraits/081.png", berry: 'Belue', ingredient_1: 'Oil', ingredient_2: 'Herb', ingredient_3: '',  },
  { id: '48', name: 'Magneton', portraitUri: "./portraits/082.png", berry: 'Belue', ingredient_1: 'Oil', ingredient_2: 'Herb', ingredient_3: '',  },
  { id: '49', name: 'Magnezone', portraitUri: "./portraits/462.png", berry: 'Belue', ingredient_1: 'Oil', ingredient_2: 'Herb', ingredient_3: '',  },
  { id: '50', name: 'Doduo', portraitUri: "./portraits/084.png", berry: 'Pamtre', ingredient_1: 'Soybeans', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '51', name: 'Dodrio', portraitUri: "./portraits/085.png", berry: 'Pamtre', ingredient_1: 'Soybeans', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '52', name: 'Gastly', portraitUri: "./portraits/092.png", berry: 'Bluk', ingredient_1: 'Herb', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '53', name: 'Haunter', portraitUri: "./portraits/093.png", berry: 'Bluk', ingredient_1: 'Herb', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '54', name: 'Gengar', portraitUri: "./portraits/094.png", berry: 'Bluk', ingredient_1: 'Herb', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '55', name: 'Onix', portraitUri: "./portraits/095.png", berry: 'Sitrus', ingredient_1: 'Tomato', ingredient_2: 'Sausage', ingredient_3: 'Potato',  },
  { id: '56', name: 'Steelix', portraitUri: "./portraits/208.png", berry: 'Belue', ingredient_1: 'Tomato', ingredient_2: 'Sausage', ingredient_3: 'Potato',  },
  { id: '57', name: 'Cubone', portraitUri: "./portraits/104.png", berry: 'Figy', ingredient_1: 'Ginger', ingredient_2: 'Cacao', ingredient_3: '',  },
  { id: '58', name: 'Marowak', portraitUri: "./portraits/105.png", berry: 'Figy', ingredient_1: 'Ginger', ingredient_2: 'Cacao', ingredient_3: '',  },
  { id: '59', name: 'Kangaskhan', portraitUri: "./portraits/115.png", berry: 'Persim', ingredient_1: 'Ginger', ingredient_2: 'Potato', ingredient_3: 'Soybeans',  },
  { id: '60', name: 'Mime Jr.', portraitUri: "./portraits/439.png", berry: 'Mago', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '61', name: 'Mr. Mime', portraitUri: "./portraits/122.png", berry: 'Mago', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '62', name: 'Pinsir', portraitUri: "./portraits/127.png", berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Apple', ingredient_3: 'Sausage',  },
  { id: '63', name: 'Ditto', portraitUri: "./portraits/132.png", berry: 'Persim', ingredient_1: 'Oil', ingredient_2: 'Leek', ingredient_3: 'Tail',  },
  { id: '64', name: 'Eevee', portraitUri: "./portraits/133.png", berry: 'Persim', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '65', name: 'Vaporeon', portraitUri: "./portraits/134.png", berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '66', name: 'Jolteon', portraitUri: "./portraits/135.png", berry: 'Grepa', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '67', name: 'Flareon', portraitUri: "./portraits/136.png", berry: 'Leppa', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '68', name: 'Espeon', portraitUri: "./portraits/196.png", berry: 'Mago', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '69', name: 'Umbreon', portraitUri: "./portraits/197.png", berry: 'Wiki', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '70', name: 'Leafeon', portraitUri: "./portraits/470.png", berry: 'Durin', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '71', name: 'Glaceon', portraitUri: "./portraits/471.png", berry: 'Rawst', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '72', name: 'Sylveon', portraitUri: "./portraits/700.png", berry: 'Pecha', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '73', name: 'Dratini', portraitUri: "./portraits/147.png", berry: 'Yache', ingredient_1: 'Herb', ingredient_2: 'Corn', ingredient_3: 'Oil',  },
  { id: '74', name: 'Dragonair', portraitUri: "./portraits/148.png", berry: 'Yache', ingredient_1: 'Herb', ingredient_2: 'Corn', ingredient_3: 'Oil',  },
  { id: '75', name: 'Dragonite', portraitUri: "./portraits/149.png", berry: 'Yache', ingredient_1: 'Herb', ingredient_2: 'Corn', ingredient_3: 'Oil',  },
  { id: '76', name: 'Chikorita', portraitUri: "./portraits/152.png", berry: 'Durin', ingredient_1: 'Cacao', ingredient_2: 'Honey', ingredient_3: 'Leek',  },
  { id: '77', name: 'Bayleef', portraitUri: "./portraits/153.png", berry: 'Durin', ingredient_1: 'Cacao', ingredient_2: 'Honey', ingredient_3: 'Leek',  },
  { id: '78', name: 'Meganium', portraitUri: "./portraits/154.png", berry: 'Durin', ingredient_1: 'Cacao', ingredient_2: 'Honey', ingredient_3: 'Leek',  },
  { id: '79', name: 'Cyndaquil', portraitUri: "./portraits/155.png", berry: 'Leppa', ingredient_1: 'Ginger', ingredient_2: 'Herb', ingredient_3: 'Oil',  },
  { id: '80', name: 'Quilava', portraitUri: "./portraits/156.png", berry: 'Leppa', ingredient_1: 'Ginger', ingredient_2: 'Herb', ingredient_3: 'Oil',  },
  { id: '81', name: 'Typhlosion', portraitUri: "./portraits/157.png", berry: 'Leppa', ingredient_1: 'Ginger', ingredient_2: 'Herb', ingredient_3: 'Oil',  },
  { id: '82', name: 'Totodile', portraitUri: "./portraits/158.png", berry: 'Oran', ingredient_1: 'Sausage', ingredient_2: 'Oil', ingredient_3: '',  },
  { id: '83', name: 'Croconaw', portraitUri: "./portraits/159.png", berry: 'Oran', ingredient_1: 'Sausage', ingredient_2: 'Oil', ingredient_3: '',  },
  { id: '84', name: 'Feraligatr', portraitUri: "./portraits/160.png", berry: 'Oran', ingredient_1: 'Sausage', ingredient_2: 'Oil', ingredient_3: '',  },
  { id: '85', name: 'Togepi', portraitUri: "./portraits/175.png", berry: 'Pecha', ingredient_1: 'Egg', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '86', name: 'Togetic', portraitUri: "./portraits/176.png", berry: 'Pecha', ingredient_1: 'Egg', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '87', name: 'Togekiss', portraitUri: "./portraits/468.png", berry: 'Pecha', ingredient_1: 'Egg', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '88', name: 'Mareep', portraitUri: "./portraits/179.png", berry: 'Grepa', ingredient_1: 'Herb', ingredient_2: 'Egg', ingredient_3: '',  },
  { id: '89', name: 'Flaaffy', portraitUri: "./portraits/180.png", berry: 'Grepa', ingredient_1: 'Herb', ingredient_2: 'Egg', ingredient_3: '',  },
  { id: '90', name: 'Ampharos', portraitUri: "./portraits/181.png", berry: 'Grepa', ingredient_1: 'Herb', ingredient_2: 'Egg', ingredient_3: '',  },
  { id: '91', name: 'Bonsly', portraitUri: "./portraits/438.png", berry: 'Sitrus', ingredient_1: 'Tomato', ingredient_2: 'Soybeans', ingredient_3: 'Mushroom',  },
  { id: '92', name: 'Sudowoodo', portraitUri: "./portraits/185.png", berry: 'Sitrus', ingredient_1: 'Tomato', ingredient_2: 'Soybeans', ingredient_3: 'Mushroom',  },
  { id: '93', name: 'Wooper', portraitUri: "./portraits/194.png", berry: 'Oran', ingredient_1: 'Mushroom', ingredient_2: 'Potato', ingredient_3: 'Sausage',  },
  { id: '94', name: 'Quagsire', portraitUri: "./portraits/195.png", berry: 'Oran', ingredient_1: 'Mushroom', ingredient_2: 'Potato', ingredient_3: 'Sausage',  },
  { id: '95', name: 'Wynaut', portraitUri: "./portraits/360.png", berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '96', name: 'Wobbuffet', portraitUri: "./portraits/202.png", berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '97', name: 'Heracross', portraitUri: "./portraits/214.png", berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Mushroom', ingredient_3: 'Sausage',  },
  { id: '98', name: 'Delibird', portraitUri: "./portraits/225.png", berry: 'Pamtre', ingredient_1: 'Egg', ingredient_2: 'Apple', ingredient_3: 'Cacao',  },
  { id: '99', name: 'Houndour', portraitUri: "./portraits/228.png", berry: 'Wiki', ingredient_1: 'Herb', ingredient_2: 'Ginger', ingredient_3: 'Leek',  },
  { id: '100', name: 'Houndoom', portraitUri: "./portraits/229.png", berry: 'Wiki', ingredient_1: 'Herb', ingredient_2: 'Ginger', ingredient_3: 'Leek',  },
  { id: '101', name: 'Raiku', portraitUri: "./portraits/243.png", berry: 'Grepa', ingredient_1: 'Sausage', ingredient_2: 'Herb', ingredient_3: 'Leek',  },
  { id: '102', name: 'Entei', portraitUri: "./portraits/244.png", berry: 'Leppa', ingredient_1: 'Oil', ingredient_2: 'Tomato', ingredient_3: 'Mushroom',  },
  { id: '103', name: 'Suicune', portraitUri: "./portraits/245.png", berry: 'Oran', ingredient_1: 'Apple', ingredient_2: 'Oil', ingredient_3: 'Corn',  },
  { id: '104', name: 'Larvitar', portraitUri: "./portraits/246.png", berry: 'Sitrus', ingredient_1: 'Ginger', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '105', name: 'Pupitar', portraitUri: "./portraits/247.png", berry: 'Sitrus', ingredient_1: 'Ginger', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '106', name: 'Tyranitar', portraitUri: "./portraits/248.png", berry: 'Wiki', ingredient_1: 'Ginger', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '107', name: 'Ralts', portraitUri: "./portraits/280.png", berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '108', name: 'Kirlia', portraitUri: "./portraits/281.png", berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '109', name: 'Gardevoir', portraitUri: "./portraits/282.png", berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '110', name: 'Gallade', portraitUri: "./portraits/475.png", berry: 'Cheri', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '111', name: 'Slakoth', portraitUri: "./portraits/287.png", berry: 'Persim', ingredient_1: 'Tomato', ingredient_2: 'Honey', ingredient_3: 'Apple',  },
  { id: '112', name: 'Vigoroth', portraitUri: "./portraits/288.png", berry: 'Persim', ingredient_1: 'Tomato', ingredient_2: 'Honey', ingredient_3: 'Apple',  },
  { id: '113', name: 'Slaking', portraitUri: "./portraits/289.png", berry: 'Persim', ingredient_1: 'Tomato', ingredient_2: 'Honey', ingredient_3: 'Apple',  },
  { id: '114', name: 'Sableye', portraitUri: "./portraits/302.png", berry: 'Wiki', ingredient_1: 'Oil', ingredient_2: 'Mushroom', ingredient_3: 'Cacao',  },
  { id: '115', name: 'Gulpin', portraitUri: "./portraits/316.png", berry: 'Chesto', ingredient_1: 'Soybeans', ingredient_2: 'Mushoom', ingredient_3: 'Honey',  },
  { id: '116', name: 'Swalot', portraitUri: "./portraits/317.png", berry: 'Chesto', ingredient_1: 'Soybeans', ingredient_2: 'Mushoom', ingredient_3: 'Honey',  },
  { id: '117', name: 'Swablu', portraitUri: "./portraits/333.png", berry: 'Pamtre', ingredient_1: 'Egg', ingredient_2: 'Soybeans', ingredient_3: 'Apple',  },
  { id: '118', name: 'Altaria', portraitUri: "./portraits/334.png", berry: 'Yache', ingredient_1: 'Egg', ingredient_2: 'Soybeans', ingredient_3: 'Apple',  },
  { id: '119', name: 'Shuppet', portraitUri: "./portraits/353.png", berry: 'Bluk', ingredient_1: 'Oil', ingredient_2: 'Ginger', ingredient_3: 'Mushroom',  },
  { id: '120', name: 'Banette', portraitUri: "./portraits/354.png", berry: 'Bluk', ingredient_1: 'Oil', ingredient_2: 'Ginger', ingredient_3: 'Mushroom',  },
  { id: '121', name: 'Absol', portraitUri: "./portraits/359.png", berry: 'Wiki', ingredient_1: 'Cacao', ingredient_2: 'Apple', ingredient_3: 'Mushroom',  },
  { id: '122', name: 'Spheal', portraitUri: "./portraits/363.png", berry: 'Rawst', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: 'Ginger',  },
  { id: '123', name: 'Sealeo', portraitUri: "./portraits/364.png", berry: 'Rawst', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: 'Ginger',  },
  { id: '124', name: 'Walrein', portraitUri: "./portraits/365.png", berry: 'Rawst', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: 'Ginger',  },
  { id: '125', name: 'Riolu', portraitUri: "./portraits/447.png", berry: 'Cheri', ingredient_1: 'Oil', ingredient_2: 'Potato', ingredient_3: 'Egg',  },
  { id: '126', name: 'Lucario', portraitUri: "./portraits/448.png", berry: 'Cheri', ingredient_1: 'Oil', ingredient_2: 'Potato', ingredient_3: 'Egg',  },
  { id: '127', name: 'Croagunk', portraitUri: "./portraits/453.png", berry: 'Chesto', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '128', name: 'Toxicroak', portraitUri: "./portraits/454.png", berry: 'Chesto', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '129', name: 'Snover', portraitUri: "./portraits/459.png", berry: 'Rawst', ingredient_1: 'Tomato', ingredient_2: 'Egg', ingredient_3: 'Mushroom',  },
  { id: '130', name: 'Abomasnow', portraitUri: "./portraits/460.png", berry: 'Rawst', ingredient_1: 'Tomato', ingredient_2: 'Egg', ingredient_3: 'Mushroom',  },
  { id: '131', name: 'Dedenne', portraitUri: "./portraits/702.png", berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Cacao', ingredient_3: 'Corn',  },
  { id: '132', name: 'Stufful', portraitUri: "./portraits/759.png", berry: 'Cheri', ingredient_1: 'Corn', ingredient_2: 'Sausage', ingredient_3: 'Egg',  },
  { id: '133', name: 'Bewear', portraitUri: "./portraits/760.png", berry: 'Cheri', ingredient_1: 'Corn', ingredient_2: 'Sausage', ingredient_3: 'Egg',  },
  { id: '134', name: 'Comfey', portraitUri: "./portraits/764.png", berry: 'Pecha', ingredient_1: 'Corn', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '135', name: 'Cramorant', portraitUri: "./portraits/845.png", berry: 'Pamtre', ingredient_1: 'Oil', ingredient_2: 'Potato', ingredient_3: 'Egg',  },
  { id: '136', name: 'Sprigatito', portraitUri: "./portraits/906.png", berry: 'Durin', ingredient_1: 'Potato', ingredient_2: 'Milk', ingredient_3: 'Ginger',  },
  { id: '137', name: 'Floragato', portraitUri: "./portraits/907.png", berry: 'Durin', ingredient_1: 'Potato', ingredient_2: 'Milk', ingredient_3: 'Ginger',  },
  { id: '138', name: 'Meowscarada', portraitUri: "./portraits/908.png", berry: 'Wiki', ingredient_1: 'Potato', ingredient_2: 'Milk', ingredient_3: 'Ginger',  },
  { id: '139', name: 'Fuecoco', portraitUri: "./portraits/909.png", berry: 'Leppa', ingredient_1: 'Apple', ingredient_2: 'Sausage', ingredient_3: 'Herb',  },
  { id: '140', name: 'Crocalor', portraitUri: "./portraits/910.png", berry: 'Leppa', ingredient_1: 'Apple', ingredient_2: 'Sausage', ingredient_3: 'Herb',  },
  { id: '141', name: 'Skeledirge', portraitUri: "./portraits/911.png", berry: 'Bluk', ingredient_1: 'Apple', ingredient_2: 'Sausage', ingredient_3: 'Herb',  },
  { id: '142', name: 'Quaxly', portraitUri: "./portraits/912.png", berry: 'Oran', ingredient_1: 'Soybeans', ingredient_2: 'Leek', ingredient_3: 'Oil',  },
  { id: '143', name: 'Quaxwell', portraitUri: "./portraits/913.png", berry: 'Oran', ingredient_1: 'Soybeans', ingredient_2: 'Leek', ingredient_3: 'Oil',  },
  { id: '144', name: 'Quaquaval', portraitUri: "./portraits/914.png", berry: 'Cheri', ingredient_1: 'Soybeans', ingredient_2: 'Leek', ingredient_3: 'Oil',  },
  { id: '145', name: 'Aggron', portraitUri: "./portraits/306.png", berry: 'Belue', ingredient_1: 'Sausage', ingredient_2: 'Coffee', ingredient_3: 'Soybeans',  },
  { id: '146', name: 'Luxray', portraitUri: "./portraits/405.png", berry: 'Grepa', ingredient_1: 'Tomato', ingredient_2: 'Oil', ingredient_3: 'Coffee',  },
  { id: '147', name: 'Vikabolt', portraitUri: "./portraits/738.png", berry: 'Lum', ingredient_1: 'Coffee', ingredient_2: 'Mushroom', ingredient_3: 'Honey',  },
]

export const typeDivergentPokedex : string[] = [
  "Venusaur",
  "Charizard",
  "Blastoise",
  "Butterfree",
  "Raticate",
  "Arbok",
  "Raichu",
  "Clefable",
  "Ninetails",
  "Wigglytuff",
  "Dugtrio",
  "Persian",
  "Golduck",
  "Primeape",
  "Arcanine",
  "Victreebel",
  "Golem",
  "Slowbro",
  "Slowking",
  "Magnezone",
  "Dodrio",
  "Gengar",
  "Onix",
  "Steelix",
  "Marowak",
  "Kangaskhan",
  "Mr. Mime",
  "Pinsir",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Espeon",
  "Umbreon",
  "Leafeon",
  "Glaceon",
  "Sylveon",
  "Dragonite",
  "Meganium",
  "Typhlosion",
  "Feraligatr",
  "Togekiss",
  "Ampharos",
  "Sudowoodo",
  "Quagsire",
  "Wobbuffet",
  "Heracross",
  "Delibird",
  "Houndoom",
  "Raiku",
  "Entei",
  "Suicune",
  "Larvitar",
  "Tyranitar",
  "Gardevoir",
  "Gallade",
  "Slaking",
  "Sableye",
  "Gulpin",
  "Swalot",
  "Swablu",
  "Altaria",
  "Banette",
  "Absol",
  "Spheal",
  "Walrein",
  "Riolu",
  "Lucario",
  "Croagunk",
  "Toxicroak",
  "Abomasnow",
  "Dedenne",
  "Bewear",
  "Comfey",
  "Cramorant",
  "Sprigatito",
  "Meowscarada",
  "Fuecoco",
  "Skeledirge",
  "Quaxly",
  "Quaquaval",
  "Aggron",
  "Luxray",
  "Vikabolt",
]

export type BoxEntry = {
  id: string,
  Owned: boolean,
  Perf: boolean,
  Pokemon: string,
}

export const pokemonBox : BoxEntry[] = [
  { id: "1", Owned: true, Perf: true, Pokemon: "Bulbasaur",  },
  { id: "2", Owned: false, Perf: false, Pokemon: "Ivysaur",  },
  { id: "3", Owned: false, Perf: false, Pokemon: "Venusaur",  },
  { id: "4", Owned: true, Perf: true, Pokemon: "Charmander",  },
  { id: "5", Owned: false, Perf: false, Pokemon: "Charmeleon",  },
  { id: "6", Owned: false, Perf: false, Pokemon: "Charizard",  },
  { id: "7", Owned: true, Perf: true, Pokemon: "Squirtle",  },
  { id: "8", Owned: true, Perf: true, Pokemon: "Wartortle",  },
  { id: "9", Owned: false, Perf: false, Pokemon: "Blastoise",  },
  { id: "10", Owned: true, Perf: true, Pokemon: "Caterpie",  },
  { id: "11", Owned: false, Perf: false, Pokemon: "Metapod",  },
  { id: "12", Owned: false, Perf: false, Pokemon: "Butterfree",  },
  { id: "13", Owned: true, Perf: false, Pokemon: "Rattata",  },
  { id: "14", Owned: false, Perf: false, Pokemon: "Raticate",  },
  { id: "15", Owned: true, Perf: true, Pokemon: "Ekans",  },
  { id: "16", Owned: false, Perf: false, Pokemon: "Arbok",  },
  { id: "17", Owned: true, Perf: false, Pokemon: "Pichu",  },
  { id: "18", Owned: true, Perf: false, Pokemon: "Pikachu",  },
  { id: "19", Owned: false, Perf: false, Pokemon: "Raichu",  },
  { id: "20", Owned: true, Perf: true, Pokemon: "Cleffa",  },
  { id: "21", Owned: false, Perf: false, Pokemon: "Clefairy",  },
  { id: "22", Owned: false, Perf: false, Pokemon: "Clefable",  },
  { id: "23", Owned: true, Perf: false, Pokemon: "Vulpix",  },
  { id: "24", Owned: false, Perf: false, Pokemon: "Ninetails",  },
  { id: "25", Owned: true, Perf: true, Pokemon: "Igglybuff",  },
  { id: "26", Owned: true, Perf: true, Pokemon: "Jigglypuff",  },
  { id: "27", Owned: false, Perf: false, Pokemon: "Wigglytuff",  },
  { id: "28", Owned: true, Perf: true, Pokemon: "Diglett",  },
  { id: "29", Owned: false, Perf: false, Pokemon: "Dugtrio",  },
  { id: "30", Owned: true, Perf: false, Pokemon: "Meowth",  },
  { id: "31", Owned: false, Perf: false, Pokemon: "Persian",  },
  { id: "32", Owned: true, Perf: true, Pokemon: "Psyduck",  },
  { id: "33", Owned: false, Perf: false, Pokemon: "Golduck",  },
  { id: "34", Owned: true, Perf: true, Pokemon: "Mankey",  },
  { id: "35", Owned: false, Perf: false, Pokemon: "Primeape",  },
  { id: "36", Owned: true, Perf: true, Pokemon: "Growlithe",  },
  { id: "37", Owned: true, Perf: true, Pokemon: "Arcanine",  },
  { id: "38", Owned: true, Perf: true, Pokemon: "Bellsprout",  },
  { id: "39", Owned: false, Perf: false, Pokemon: "Weepinbell",  },
  { id: "40", Owned: false, Perf: false, Pokemon: "Victreebel",  },
  { id: "41", Owned: true, Perf: true, Pokemon: "Geodude",  },
  { id: "42", Owned: true, Perf: false, Pokemon: "Graveler",  },
  { id: "43", Owned: false, Perf: false, Pokemon: "Golem",  },
  { id: "44", Owned: true, Perf: true, Pokemon: "Slowpoke",  },
  { id: "45", Owned: false, Perf: false, Pokemon: "Slowbro",  },
  { id: "46", Owned: false, Perf: false, Pokemon: "Slowking",  },
  { id: "47", Owned: true, Perf: false, Pokemon: "Magnemite",  },
  { id: "48", Owned: false, Perf: false, Pokemon: "Magneton",  },
  { id: "49", Owned: false, Perf: false, Pokemon: "Magnezone",  },
  { id: "50", Owned: true, Perf: false, Pokemon: "Doduo",  },
  { id: "51", Owned: false, Perf: false, Pokemon: "Dodrio",  },
  { id: "52", Owned: true, Perf: false, Pokemon: "Gastly",  },
  { id: "53", Owned: false, Perf: false, Pokemon: "Haunter",  },
  { id: "54", Owned: false, Perf: false, Pokemon: "Gengar",  },
  { id: "55", Owned: false, Perf: false, Pokemon: "Onix",  },
  { id: "56", Owned: false, Perf: false, Pokemon: "Steelix",  },
  { id: "57", Owned: true, Perf: true, Pokemon: "Cubone",  },
  { id: "58", Owned: false, Perf: false, Pokemon: "Marowak",  },
  { id: "59", Owned: false, Perf: false, Pokemon: "Kangaskhan",  },
  { id: "60", Owned: true, Perf: false, Pokemon: "Mime Jr.",  },
  { id: "61", Owned: false, Perf: false, Pokemon: "Mr. Mime",  },
  { id: "62", Owned: true, Perf: false, Pokemon: "Pinsir",  },
  { id: "63", Owned: true, Perf: false, Pokemon: "Ditto",  },
  { id: "64", Owned: true, Perf: false, Pokemon: "Eevee",  },
  { id: "65", Owned: false, Perf: false, Pokemon: "Vaporeon",  },
  { id: "66", Owned: false, Perf: false, Pokemon: "Jolteon",  },
  { id: "67", Owned: false, Perf: false, Pokemon: "Flareon",  },
  { id: "68", Owned: false, Perf: false, Pokemon: "Espeon",  },
  { id: "69", Owned: false, Perf: false, Pokemon: "Umbreon",  },
  { id: "70", Owned: false, Perf: false, Pokemon: "Leafeon",  },
  { id: "71", Owned: false, Perf: false, Pokemon: "Glaceon",  },
  { id: "72", Owned: false, Perf: false, Pokemon: "Sylveon",  },
  { id: "73", Owned: false, Perf: false, Pokemon: "Dratini",  },
  { id: "74", Owned: false, Perf: false, Pokemon: "Dragonair",  },
  { id: "75", Owned: false, Perf: false, Pokemon: "Dragonite",  },
  { id: "76", Owned: true, Perf: true, Pokemon: "Chikorita",  },
  { id: "77", Owned: true, Perf: true, Pokemon: "Bayleef",  },
  { id: "78", Owned: false, Perf: false, Pokemon: "Meganium",  },
  { id: "79", Owned: true, Perf: false, Pokemon: "Cyndaquil",  },
  { id: "80", Owned: false, Perf: false, Pokemon: "Quilava",  },
  { id: "81", Owned: false, Perf: false, Pokemon: "Typhlosion",  },
  { id: "82", Owned: true, Perf: true, Pokemon: "Totodile",  },
  { id: "83", Owned: false, Perf: false, Pokemon: "Croconaw",  },
  { id: "84", Owned: false, Perf: false, Pokemon: "Feraligatr",  },
  { id: "85", Owned: true, Perf: true, Pokemon: "Togepi",  },
  { id: "86", Owned: false, Perf: false, Pokemon: "Togetic",  },
  { id: "87", Owned: false, Perf: false, Pokemon: "Togekiss",  },
  { id: "88", Owned: true, Perf: true, Pokemon: "Mareep",  },
  { id: "89", Owned: false, Perf: false, Pokemon: "Flaaffy",  },
  { id: "90", Owned: false, Perf: false, Pokemon: "Ampharos",  },
  { id: "91", Owned: true, Perf: false, Pokemon: "Bonsly",  },
  { id: "92", Owned: false, Perf: false, Pokemon: "Sudowoodo",  },
  { id: "93", Owned: true, Perf: true, Pokemon: "Wooper",  },
  { id: "94", Owned: false, Perf: false, Pokemon: "Quagsire",  },
  { id: "95", Owned: true, Perf: true, Pokemon: "Wynaut",  },
  { id: "96", Owned: true, Perf: false, Pokemon: "Wobbuffet",  },
  { id: "97", Owned: true, Perf: false, Pokemon: "Heracross",  },
  { id: "98", Owned: true, Perf: false, Pokemon: "Delibird",  },
  { id: "99", Owned: true, Perf: false, Pokemon: "Houndour",  },
  { id: "100", Owned: false, Perf: false, Pokemon: "Houndoom",  },
  { id: "101", Owned: true, Perf: true, Pokemon: "Raiku",  },
  { id: "102", Owned: true, Perf: true, Pokemon: "Entei",  },
  { id: "103", Owned: false, Perf: false, Pokemon: "Suicune",  },
  { id: "104", Owned: true, Perf: false, Pokemon: "Larvitar",  },
  { id: "105", Owned: false, Perf: false, Pokemon: "Pupitar",  },
  { id: "106", Owned: false, Perf: false, Pokemon: "Tyranitar",  },
  { id: "107", Owned: false, Perf: false, Pokemon: "Ralts",  },
  { id: "108", Owned: false, Perf: false, Pokemon: "Kirlia",  },
  { id: "109", Owned: false, Perf: false, Pokemon: "Gardevoir",  },
  { id: "110", Owned: false, Perf: false, Pokemon: "Gallade",  },
  { id: "111", Owned: true, Perf: false, Pokemon: "Slakoth",  },
  { id: "112", Owned: false, Perf: false, Pokemon: "Vigoroth",  },
  { id: "113", Owned: false, Perf: false, Pokemon: "Slaking",  },
  { id: "114", Owned: false, Perf: false, Pokemon: "Sableye",  },
  { id: "115", Owned: true, Perf: false, Pokemon: "Gulpin",  },
  { id: "116", Owned: false, Perf: false, Pokemon: "Swalot",  },
  { id: "117", Owned: true, Perf: true, Pokemon: "Swablu",  },
  { id: "118", Owned: false, Perf: false, Pokemon: "Altaria",  },
  { id: "119", Owned: true, Perf: false, Pokemon: "Shuppet",  },
  { id: "120", Owned: false, Perf: false, Pokemon: "Banette",  },
  { id: "121", Owned: false, Perf: false, Pokemon: "Absol",  },
  { id: "122", Owned: true, Perf: true, Pokemon: "Spheal",  },
  { id: "123", Owned: false, Perf: false, Pokemon: "Sealeo",  },
  { id: "124", Owned: false, Perf: false, Pokemon: "Walrein",  },
  { id: "125", Owned: true, Perf: false, Pokemon: "Riolu",  },
  { id: "126", Owned: false, Perf: false, Pokemon: "Lucario",  },
  { id: "127", Owned: true, Perf: false, Pokemon: "Croagunk",  },
  { id: "128", Owned: false, Perf: false, Pokemon: "Toxicroak",  },
  { id: "129", Owned: true, Perf: true, Pokemon: "Snover",  },
  { id: "130", Owned: false, Perf: false, Pokemon: "Abomasnow",  },
  { id: "131", Owned: true, Perf: false, Pokemon: "Dedenne",  },
  { id: "132", Owned: false, Perf: false, Pokemon: "Stufful",  },
  { id: "133", Owned: false, Perf: false, Pokemon: "Bewear",  },
  { id: "134", Owned: true, Perf: true, Pokemon: "Comfey",  },
  { id: "135", Owned: false, Perf: false, Pokemon: "Cramorant",  },
  { id: "136", Owned: true, Perf: false, Pokemon: "Sprigatito",  },
  { id: "137", Owned: false, Perf: false, Pokemon: "Floragato",  },
  { id: "138", Owned: false, Perf: false, Pokemon: "Meowscarada",  },
  { id: "139", Owned: true, Perf: true, Pokemon: "Fuecoco",  },
  { id: "140", Owned: false, Perf: false, Pokemon: "Crocalor",  },
  { id: "141", Owned: false, Perf: false, Pokemon: "Skeledirge",  },
  { id: "142", Owned: true, Perf: true, Pokemon: "Quaxly",  },
  { id: "143", Owned: false, Perf: false, Pokemon: "Quaxwell",  },
  { id: "144", Owned: false, Perf: false, Pokemon: "Quaquaval",  },
  { id: "145", Owned: false, Perf: false, Pokemon: "Aggron",  },
  { id: "146", Owned: false, Perf: false, Pokemon: "Luxray",  },
  { id: "147", Owned: false, Perf: false, Pokemon: "Vikabolt",  },
]

export type BerryTypes = {
  index: string,
  berryName: string,
  berryImageUri: string,
  typeName: string,
  typeImageUri: string,
}

export const berryTypes : BerryTypes[] = [
  { index: '1', berryName: "Persim", typeName: "Normal", berryImageUri: "./berries/persimberry.png", typeImageUri: "./types/normal.png" },
  { index: '2', berryName: "Leppa", typeName: "Fire", berryImageUri: "./berries/leppaberry.png", typeImageUri: "./types/fire.png" },
  { index: '3', berryName: "Oran", typeName: "Water", berryImageUri: "./berries/oranberry.png", typeImageUri: "./types/water.png" },
  { index: '4', berryName: "Grepa", typeName: "Electric", berryImageUri: "./berries/grepaberry.png", typeImageUri: "./types/electric.png" },
  { index: '5', berryName: "Durin", typeName: "Grass", berryImageUri: "./berries/durinberry.png", typeImageUri: "./types/grass.png" },
  { index: '6', berryName: "Rawst", typeName: "Ice", berryImageUri: "./berries/rawstberry.png", typeImageUri: "./types/ice.png" },
  { index: '7', berryName: "Cheri", typeName: "Fighting", berryImageUri: "./berries/cheriberry.png", typeImageUri: "./types/fighting.png" },
  { index: '8', berryName: "Chesto", typeName: "Poison", berryImageUri: "./berries/chestoberry.png", typeImageUri: "./types/poison.png" },
  { index: '9', berryName: "Figy", typeName: "Ground", berryImageUri: "./berries/figyberry.png", typeImageUri: "./types/ground.png" },
  { index: '10', berryName: "Pamtre", typeName: "Flying", berryImageUri: "./berries/pamtreberry.png", typeImageUri: "./types/flying.png" },
  { index: '11', berryName: "Mago", typeName: "Psychic", berryImageUri: "./berries/magoberry.png", typeImageUri: "./types/psychic.png" },
  { index: '12', berryName: "Lum", typeName: "Bug", berryImageUri: "./berries/lumberry.png", typeImageUri: "./types/bug.png" },
  { index: '13', berryName: "Sitrus", typeName: "Rock", berryImageUri: "./berries/sitrusberry.png", typeImageUri: "./types/rock.png" },
  { index: '14', berryName: "Bluk", typeName: "Ghost", berryImageUri: "./berries/blukberry.png", typeImageUri: "./types/ghost.png" },
  { index: '15', berryName: "Yache", typeName: "Dragon", berryImageUri: "./berries/yacheberry.png", typeImageUri: "./types/dragon.png" },
  { index: '16', berryName: "Wiki", typeName: "Dark", berryImageUri: "./berries/wikiberry.png", typeImageUri: "./types/dark.png" },
  { index: '17', berryName: "Belue", typeName: "Steel", berryImageUri: "./berries/belueberry.png", typeImageUri: "./types/steel.png" },
  { index: '18', berryName: "Pecha", typeName: "Fairy", berryImageUri: "./berries/pechaberry.png", typeImageUri: "./types/fairy.png" },
]

export type Recipe = {
  key: string,
  Type: string,
  Recipe: string,
  Apple: string,
  Honey: string,
  Milk: string,
  Ginger: string,
  Oil: string,
  Cacao: string,
  Egg: string,
  Soybeans: string,
  Potato: string,
  Tomato: string,
  Mushroom: string,
  Tail: string,
  Herb: string,
  Leek: string,
  Corn: string,
  Sausage: string,
  Coffee?: string,
  Total_ingredients: string,
}

export type Ingredients = {
  name: string,
  uri?: string | undefined,
}

export const ingredients: Ingredients[] = [
  {name: "Apple", uri: "./ingredients/fancyapple.png"},
  {name: "Honey", uri: "./ingredients/honey.png"},
  {name: "Milk", uri: "./ingredients/moomoomilk.png"},
  {name: "Ginger", uri: "./ingredients/warmingginger.png"},
  {name: "Oil", uri: "./ingredients/pureoil.png"},
  {name: "Cacao", uri: "./ingredients/soothingcacao.png"},
  {name: "Egg", uri: "./ingredients/fancyegg.png"},
  {name: "Soybeans", uri: "./ingredients/greengrasssoybeans.png"},
  {name: "Potato", uri: "./ingredients/softpotato.png"},
  {name: "Tomato", uri: "./ingredients/snoozytomato.png"},
  {name: "Mushroom", uri: "./ingredients/tastymushroom.png"},
  {name: "Tail", uri: "./ingredients/slowpoketail.png"},
  {name: "Herb", uri: "./ingredients/fieryherb.png"},
  {name: "Leek", uri: "./ingredients/largeleek.png"},
  {name: "Corn", uri: "./ingredients/greengrasscorn.png"},
  {name: "Sausage", uri: "./ingredients/beansausage.png"},
  {name: "Coffee", uri: "./ingredients/rousingcoffee.png"},
]

export const recipes : Recipe[] = [
  { key: '0', Type: "Curry", Recipe: "Fancy Apple Curry", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '1', Type: "Curry", Recipe: "Simple Chowder", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '2', Type: "Curry", Recipe: "Beanburger Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "7",  },
  { key: '3', Type: "Curry", Recipe: "Mild Honey Curry", Apple: "0", Honey: "7", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '4', Type: "Curry", Recipe: "Solar Power Tomato Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "10", Mushroom: "0", Tail: "0", Herb: "5", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '5', Type: "Curry", Recipe: "Drought Katsu Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "10", Total_ingredients: "15",  },
  { key: '6', Type: "Curry", Recipe: "Hearty Cheeseburger Curry", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "16",  },
  { key: '7', Type: "Curry", Recipe: "Melty Omelette Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "10", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '8', Type: "Curry", Recipe: "Soft Potato Chowder", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "4", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '9', Type: "Curry", Recipe: "Spore Mushroom Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "14", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '10', Type: "Curry", Recipe: "Bulk Up Bean Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "4", Soybeans: "12", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "4", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "26",  },
  { key: '11', Type: "Curry", Recipe: "Limber Corn Stew", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "14", Sausage: "0", Total_ingredients: "30",  },
  { key: '12', Type: "Curry", Recipe: "Spicy Leek Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "8", Leek: "14", Corn: "0", Sausage: "0", Total_ingredients: "32",  },
  { key: '13', Type: "Curry", Recipe: "Grilled Tail Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "8", Herb: "25", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '14', Type: "Curry", Recipe: "Egg Bomb Curry", Apple: "11", Honey: "12", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "0", Potato: "4", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '15', Type: "Curry", Recipe: "Ninja Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "24", Potato: "0", Tomato: "0", Mushroom: "5", Tail: "0", Herb: "0", Leek: "12", Corn: "0", Sausage: "9", Total_ingredients: "50",  },
  { key: '16', Type: "Curry", Recipe: "Dream Eater Butter Curry", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "12", Egg: "0", Soybeans: "0", Potato: "18", Tomato: "15", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '17', Type: "Curry", Recipe: "Inferno Corn Keema Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "12", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "27", Leek: "0", Corn: "14", Sausage: "24", Total_ingredients: "77",  },
  { key: '18', Type: "Salad", Recipe: "Bean Ham Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "8",  },
  { key: '19', Type: "Salad", Recipe: "Snoozy Tomato Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '20', Type: "Salad", Recipe: "Fancy Apple Salad", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '21', Type: "Salad", Recipe: "Immunity Leek Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "5", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "10", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '22', Type: "Salad", Recipe: "Snow Cloak Caesar Salad", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "16",  },
  { key: '23', Type: "Salad", Recipe: "Water Veil Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '24', Type: "Salad", Recipe: "Heat Wave Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "10", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "6", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '25', Type: "Salad", Recipe: "Fury Attack Corn Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "9", Sausage: "0", Total_ingredients: "17",  },
  { key: '26', Type: "Salad", Recipe: "Superpower Extreme Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "6", Oil: "0", Cacao: "0", Egg: "5", Soybeans: "0", Potato: "3", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '27', Type: "Salad", Recipe: "Moomoo Caprese Salad", Apple: "0", Honey: "0", Milk: "12", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '28', Type: "Salad", Recipe: "Contrary Chocolate Meat Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "14", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '29', Type: "Salad", Recipe: "Dazzling Apple Cheese Salad", Apple: "15", Honey: "0", Milk: "5", Ginger: "0", Oil: "3", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '30', Type: "Salad", Recipe: "Slowpoke Tail Pepper Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "10", Herb: "10", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "25",  },
  { key: '31', Type: "Salad", Recipe: "Spore Mushroom Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "17", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '32', Type: "Salad", Recipe: "Overheat Ginger Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "17", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '33', Type: "Salad", Recipe: "Gluttony Potato Salad", Apple: "6", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "9", Soybeans: "0", Potato: "14", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "36",  },
  { key: '34', Type: "Salad", Recipe: "Calm Mind Fruit Salad", Apple: "21", Honey: "16", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "12", Sausage: "0", Total_ingredients: "49",  },
  { key: '35', Type: "Salad", Recipe: "Ninja Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "19", Potato: "0", Tomato: "0", Mushroom: "12", Tail: "0", Herb: "0", Leek: "15", Corn: "0", Sausage: "0", Total_ingredients: "57",  },
  { key: '36', Type: "Salad", Recipe: "Greengrass Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "22", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "14", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "17", Sausage: "0", Total_ingredients: "62",  },
  { key: '37', Type: "Dessert", Recipe: "Warm Moomoo Milk", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '38', Type: "Dessert", Recipe: "Fancy Apple Juice", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '39', Type: "Dessert", Recipe: "Craft Soda Pop", Apple: "0", Honey: "9", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "9",  },
  { key: '40', Type: "Dessert", Recipe: "Fluffy Sweet Potatoes", Apple: "0", Honey: "0", Milk: "5", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "14",  },
  { key: '41', Type: "Dessert", Recipe: "Cloud Nine Soy Cake", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "7", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '42', Type: "Dessert", Recipe: "Ember Ginger Tea", Apple: "7", Honey: "0", Milk: "0", Ginger: "9", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '43', Type: "Dessert", Recipe: "Lucky Chant Apple Pie", Apple: "12", Honey: "0", Milk: "4", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '44', Type: "Dessert", Recipe: "Stalwart Vegetable Juice", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '45', Type: "Dessert", Recipe: "Huge Power Soy Donuts", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "12", Cacao: "7", Egg: "0", Soybeans: "16", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '46', Type: "Dessert", Recipe: "Petal Dance Chocolate Tart", Apple: "11", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "11", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '47', Type: "Dessert", Recipe: "Hustle Protein Smoothie", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '48', Type: "Dessert", Recipe: "Big Malasada", Apple: "0", Honey: "6", Milk: "7", Ginger: "0", Oil: "10", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '49', Type: "Dessert", Recipe: "Sweet Scent Chocolate Cake", Apple: "0", Honey: "9", Milk: "7", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '50', Type: "Dessert", Recipe: "Steadfast Ginger Cookies", Apple: "0", Honey: "14", Milk: "0", Ginger: "12", Oil: "0", Cacao: "5", Egg: "4", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '51', Type: "Dessert", Recipe: "Lovely Kiss Smoothie", Apple: "11", Honey: "7", Milk: "9", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '52', Type: "Dessert", Recipe: "Neroli's Restorative Tea", Apple: "15", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "9", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '53', Type: "Dessert", Recipe: "Explosion Popcorn", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "14", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "15", Sausage: "0", Total_ingredients: "36",  },
  { key: '54', Type: "Dessert", Recipe: "Jigglypuff's Fruity Flan", Apple: "10", Honey: "20", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "15", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '55', Type: "Dessert", Recipe: "Teatime Corn Scones", Apple: "20", Honey: "0", Milk: "9", Ginger: "20", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "18", Sausage: "0", Total_ingredients: "67",  },
  { key: '56', Type: "Dessert", Recipe: "Flower Gift Macarons", Apple: "0", Honey: "17", Milk: "10", Ginger: "0", Oil: "0", Cacao: "25", Egg: "25", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "77",  },
  { key: '57', Type: "Curry", Recipe: "Dizzy Punch Spicy Curry", Apple: "0", Honey: "11", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "11", Leek: "0", Corn: "0", Sausage: "0", Coffee: "11", Total_ingredients: "33",  },
  { key: '58', Type: "Curry", Recipe: "Hidden Power Perk-Up Stew", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "28", Potato: "0", Tomato: "25", Mushroom: "23", Tail: "0", Herb: "11", Leek: "0", Corn: "0", Sausage: "0", Coffee: "16", Total_ingredients: "?",  },
  { key: '59', Type: "Salad", Recipe: "Defiant Coffee-Dressed Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "22", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "22", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "28", Coffee: "28", Total_ingredients: "?",  },
  { key: '60', Type: "Dessert", Recipe: "Early Bird Coffee Jelly", Apple: "0", Honey: "12", Milk: "14", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Coffee: "16", Total_ingredients: "?",  },
  { key: '61', Type: "Dessert", Recipe: "Zing Zap Spiced Cola", Apple: "35", Honey: "0", Milk: "0", Ginger: "20", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "20", Corn: "0", Sausage: "0", Coffee: "12", Total_ingredients: "?",  },
]

export type TypeGroup = {
  key: string,
  pokemon: string[],
  default: string,
  berry: string,
}

export const typeGroups : TypeGroup[] = [
  { key: "Bulbasaur_Durin", pokemon: [ "Bulbasaur", "Ivysaur", "Venusaur",  ], default: "Venusaur", berry: "Durin",  },
  { key: "Charmander_Leppa", pokemon: [ "Charmander", "Charmeleon", "Charizard",  ], default: "Charizard", berry: "Leppa",  },
  { key: "Squirtle_Oran", pokemon: [ "Squirtle", "Wartortle", "Blastoise",  ], default: "Blastoise", berry: "Oran",  },
  { key: "Caterpie_Lum", pokemon: [ "Caterpie", "Metapod", "Butterfree",  ], default: "Butterfree", berry: "Lum",  },
  { key: "Rattata_Persim", pokemon: [ "Rattata", "Raticate",  ], default: "Raticate", berry: "Persim",  },
  { key: "Ekans_Chesto", pokemon: [ "Ekans", "Arbok",  ], default: "Arbok", berry: "Chesto",  },
  { key: "Pichu_Grepa", pokemon: [ "Pichu", "Pikachu", "Raichu",  ], default: "Raichu", berry: "Grepa",  },
  { key: "Cleffa_Pecha", pokemon: [ "Cleffa", "Clefairy", "Clefable",  ], default: "Clefable", berry: "Pecha",  },
  { key: "Vulpix_Leppa", pokemon: [ "Vulpix", "Ninetails",  ], default: "Ninetails", berry: "Leppa",  },
  { key: "Igglybuff_Pecha", pokemon: [ "Igglybuff", "Jigglypuff", "Wigglytuff",  ], default: "Wigglytuff", berry: "Pecha",  },
  { key: "Diglett_Figy", pokemon: [ "Diglett", "Dugtrio",  ], default: "Dugtrio", berry: "Figy",  },
  { key: "Meowth_Persim", pokemon: [ "Meowth", "Persian",  ], default: "Persian", berry: "Persim",  },
  { key: "Psyduck_Oran", pokemon: [ "Psyduck", "Golduck",  ], default: "Golduck", berry: "Oran",  },
  { key: "Mankey_Cheri", pokemon: [ "Mankey", "Primeape",  ], default: "Primeape", berry: "Cheri",  },
  { key: "Growlithe_Leppa", pokemon: [ "Growlithe", "Arcanine",  ], default: "Arcanine", berry: "Leppa",  },
  { key: "Bellsprout_Durin", pokemon: [ "Bellsprout", "Weepinbell", "Victreebel",  ], default: "Victreebel", berry: "Durin",  },
  { key: "Geodude_Sitrus", pokemon: [ "Geodude", "Graveler", "Golem",  ], default: "Golem", berry: "Sitrus",  },
  { key: "Slowpoke_Oran", pokemon: [ "Slowpoke", "Slowbro", "Slowking",  ], default: "Slowpoke", berry: "Oran",  },
  { key: "Magnemite_Belue", pokemon: [ "Magnemite", "Magneton", "Magnezone",  ], default: "Magnezone", berry: "Belue",  },
  { key: "Doduo_Pamtre", pokemon: [ "Doduo", "Dodrio",  ], default: "Dodrio", berry: "Pamtre",  },
  { key: "Gastly_Bluk", pokemon: [ "Gastly", "Haunter", "Gengar",  ], default: "Gengar", berry: "Bluk",  },
  { key: "Onix_Sitrus", pokemon: [ "Onix",  ], default: "Onix", berry: "Sitrus",  },
  { key: "Onix_Belue", pokemon: [ "Steelix",  ], default: "Steelix", berry: "Belue",  },
  { key: "Cubone_Figy", pokemon: [ "Cubone", "Marowak",  ], default: "Marowak", berry: "Figy",  },
  { key: "Kangaskhan_Persim", pokemon: [ "Kangaskhan",  ], default: "Kangaskhan", berry: "Persim",  },
  { key: "Mime Jr._Mago", pokemon: [ "Mime Jr.", "Mr. Mime",  ], default: "Mr. Mime", berry: "Mago",  },
  { key: "Pinsir_Lum", pokemon: [ "Pinsir",  ], default: "Pinsir", berry: "Lum",  },
  { key: "Ditto_Persim", pokemon: [ "Ditto",  ], default: "Ditto", berry: "Persim",  },
  { key: "Eevee_Persim", pokemon: [ "Eevee",  ], default: "Eevee", berry: "Persim",  },
  { key: "Eevee_Oran", pokemon: [ "Vaporeon",  ], default: "Vaporeon", berry: "Oran",  },
  { key: "Eevee_Grepa", pokemon: [ "Jolteon",  ], default: "Jolteon", berry: "Grepa",  },
  { key: "Eevee_Leppa", pokemon: [ "Flareon",  ], default: "Flareon", berry: "Leppa",  },
  { key: "Eevee_Mago", pokemon: [ "Espeon",  ], default: "Espeon", berry: "Mago",  },
  { key: "Eevee_Wiki", pokemon: [ "Umbreon",  ], default: "Umbreon", berry: "Wiki",  },
  { key: "Eevee_Durin", pokemon: [ "Leafeon",  ], default: "Leafeon", berry: "Durin",  },
  { key: "Eevee_Rawst", pokemon: [ "Glaceon",  ], default: "Glaceon", berry: "Rawst",  },
  { key: "Eevee_Pecha", pokemon: [ "Sylveon",  ], default: "Sylveon", berry: "Pecha",  },
  { key: "Dratini_Yache", pokemon: [ "Dratini", "Dragonair", "Dragonite",  ], default: "Dragonite", berry: "Yache",  },
  { key: "Chikorita_Durin", pokemon: [ "Chikorita", "Bayleef", "Meganium",  ], default: "Meganium", berry: "Durin",  },
  { key: "Cyndaquil_Leppa", pokemon: [ "Cyndaquil", "Quilava", "Typhlosion",  ], default: "Typhlosion", berry: "Leppa",  },
  { key: "Totodile_Oran", pokemon: [ "Totodile", "Croconaw", "Feraligatr",  ], default: "Feraligatr", berry: "Oran",  },
  { key: "Togepi_Pecha", pokemon: [ "Togepi", "Togetic", "Togekiss",  ], default: "Togekiss", berry: "Pecha",  },
  { key: "Mareep_Grepa", pokemon: [ "Mareep", "Flaaffy", "Ampharos",  ], default: "Ampharos", berry: "Grepa",  },
  { key: "Bonsly_Sitrus", pokemon: [ "Bonsly", "Sudowoodo",  ], default: "Sudowoodo", berry: "Sitrus",  },
  { key: "Wooper_Oran", pokemon: [ "Wooper", "Quagsire",  ], default: "Quagsire", berry: "Oran",  },
  { key: "Wynaut_Mago", pokemon: [ "Wynaut", "Wobbuffet",  ], default: "Wobbuffet", berry: "Mago",  },
  { key: "Heracross_Lum", pokemon: [ "Heracross",  ], default: "Heracross", berry: "Lum",  },
  { key: "Delibird_Pamtre", pokemon: [ "Delibird",  ], default: "Delibird", berry: "Pamtre",  },
  { key: "Houndour_Wiki", pokemon: [ "Houndour", "Houndoom",  ], default: "Houndoom", berry: "Wiki",  },
  { key: "Raiku_Grepa", pokemon: [ "Raiku",  ], default: "Raiku", berry: "Grepa",  },
  { key: "Entei_Leppa", pokemon: [ "Entei",  ], default: "Entei", berry: "Leppa",  },
  { key: "Suicune_Oran", pokemon: [ "Suicune",  ], default: "Suicune", berry: "Oran",  },
  { key: "Larvitar_Sitrus", pokemon: [ "Larvitar", "Pupitar",  ], default: "Larvitar", berry: "Sitrus",  },
  { key: "Larvitar_Wiki", pokemon: [ "Tyranitar",  ], default: "Tyranitar", berry: "Wiki",  },
  { key: "Ralts_Mago", pokemon: [ "Ralts", "Kirlia", "Gardevoir",  ], default: "Gardevoir", berry: "Mago",  },
  { key: "Ralts_Cheri", pokemon: [ "Gallade",  ], default: "Gallade", berry: "Cheri",  },
  { key: "Slakoth_Persim", pokemon: [ "Slakoth", "Vigoroth", "Slaking",  ], default: "Slaking", berry: "Persim",  },
  { key: "Aron_Belue", pokemon: [ "Aron", "Lairon", "Aggron",  ], default: "Aggron", berry: "Belue",  },
  { key: "Sableye_Wiki", pokemon: [ "Sableye",  ], default: "Sableye", berry: "Wiki",  },
  { key: "Gulpin_Chesto", pokemon: [ "Gulpin", "Swalot",  ], default: "Swalot", berry: "Chesto",  },
  { key: "Swablu_Pamtre", pokemon: [ "Swablu",  ], default: "Swablu", berry: "Pamtre",  },
  { key: "Swablu_Yache", pokemon: [ "Altaria",  ], default: "Altaria", berry: "Yache",  },
  { key: "Shuppet_Bluk", pokemon: [ "Shuppet", "Banette",  ], default: "Banette", berry: "Bluk",  },
  { key: "Absol_Wiki", pokemon: [ "Absol",  ], default: "Absol", berry: "Wiki",  },
  { key: "Spheal_Rawst", pokemon: [ "Spheal", "Sealeo", "Walrein",  ], default: "Walrein", berry: "Rawst",  },
  { key: "Shinx_Grepa", pokemon: [ "Shinx", "Luxio", "Luxray",  ], default: "Luxray", berry: "Grepa",  },
  { key: "Riolu_Cheri", pokemon: [ "Riolu", "Lucario",  ], default: "Lucario", berry: "Cheri",  },
  { key: "Croagunk_Chesto", pokemon: [ "Croagunk", "Toxicroak",  ], default: "Toxicroak", berry: "Chesto",  },
  { key: "Snover_Rawst", pokemon: [ "Snover", "Abomasnow",  ], default: "Abomasnow", berry: "Rawst",  },
  { key: "Dedenne_Grepa", pokemon: [ "Dedenne",  ], default: "Dedenne", berry: "Grepa",  },
  { key: "Grubbin_Lum", pokemon: [ "Grubbin", "Charjabug", "Vikabolt",  ], default: "Vikabolt", berry: "Lum",  },
  { key: "Stufful_Cheri", pokemon: [ "Stufful", "Bewear",  ], default: "Bewear", berry: "Cheri",  },
  { key: "Comfey_Pecha", pokemon: [ "Comfey",  ], default: "Comfey", berry: "Pecha",  },
  { key: "Cramorant_Pamtre", pokemon: [ "Cramorant",  ], default: "Cramorant", berry: "Pamtre",  },
  { key: "Sprigatito_Durin", pokemon: [ "Sprigatito", "Floragato",  ], default: "Sprigatito", berry: "Durin",  },
  { key: "Sprigatito_Wiki", pokemon: [ "Meowscarada",  ], default: "Meowscarada", berry: "Wiki",  },
  { key: "Fuecoco_Leppa", pokemon: [ "Fuecoco", "Crocalor",  ], default: "Fuecoco", berry: "Leppa",  },
  { key: "Fuecoco_Bluk", pokemon: [ "Skeledirge",  ], default: "Skeledirge", berry: "Bluk",  },
  { key: "Quaxly_Oran", pokemon: [ "Quaxly", "Quaxwell",  ], default: "Quaxly", berry: "Oran",  },
  { key: "Quaxly_Cheri", pokemon: [ "Quaquaval",  ], default: "Quaquaval", berry: "Cheri",  },
]
