
export type Pokemon = {
  id: string,
  name: string,
  berry: string,
  ingredient_1: string,
  ingredient_2: string,
  ingredient_3: string,
}

export const pokedex : Pokemon[] = [
  { id: '1', name: 'Bulbasaur', berry: 'Durin', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Potato',  },
  { id: '2', name: 'Ivysaur', berry: 'Durin', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Potato',  },
  { id: '3', name: 'Venusaur', berry: 'Durin', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Potato',  },
  { id: '4', name: 'Charmander', berry: 'Leppa', ingredient_1: 'Sausage', ingredient_2: 'Ginger', ingredient_3: 'Herb',  },
  { id: '5', name: 'Charmeleon', berry: 'Leppa', ingredient_1: 'Sausage', ingredient_2: 'Ginger', ingredient_3: 'Herb',  },
  { id: '6', name: 'Charizard', berry: 'Leppa', ingredient_1: 'Sausage', ingredient_2: 'Ginger', ingredient_3: 'Herb',  },
  { id: '7', name: 'Squirtle', berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '8', name: 'Wartortle', berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '9', name: 'Blastoise', berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '10', name: 'Caterpie', berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Soybeans',  },
  { id: '11', name: 'Metapod', berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Soybeans',  },
  { id: '12', name: 'Butterfree', berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Tomato', ingredient_3: 'Soybeans',  },
  { id: '13', name: 'Rattata', berry: 'Persim', ingredient_1: 'Apple', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '14', name: 'Raticate', berry: 'Persim', ingredient_1: 'Apple', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '15', name: 'Ekans', berry: 'Chesto', ingredient_1: 'Sausage', ingredient_2: 'Egg', ingredient_3: 'Herb',  },
  { id: '16', name: 'Arbok', berry: 'Chesto', ingredient_1: 'Sausage', ingredient_2: 'Egg', ingredient_3: 'Herb',  },
  { id: '17', name: 'Pichu', berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Ginger', ingredient_3: 'Egg',  },
  { id: '18', name: 'Pikachu', berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Ginger', ingredient_3: 'Egg',  },
  { id: '19', name: 'Raichu', berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Ginger', ingredient_3: 'Egg',  },
  { id: '20', name: 'Cleffa', berry: 'Pecha', ingredient_1: 'Apple', ingredient_2: 'Honey', ingredient_3: 'Soybeans',  },
  { id: '21', name: 'Clefairy', berry: 'Pecha', ingredient_1: 'Apple', ingredient_2: 'Honey', ingredient_3: 'Soybeans',  },
  { id: '22', name: 'Clefable', berry: 'Pecha', ingredient_1: 'Apple', ingredient_2: 'Honey', ingredient_3: 'Soybeans',  },
  { id: '23', name: 'Vulpix', berry: 'Leppa', ingredient_1: 'Soybeans', ingredient_2: 'Corn', ingredient_3: 'Potato',  },
  { id: '24', name: 'Ninetails', berry: 'Leppa', ingredient_1: 'Soybeans', ingredient_2: 'Corn', ingredient_3: 'Potato',  },
  { id: '25', name: 'Igglybuff', berry: 'Pecha', ingredient_1: 'Honey', ingredient_2: 'Oil', ingredient_3: 'Cacao',  },
  { id: '26', name: 'Jigglypuff', berry: 'Pecha', ingredient_1: 'Honey', ingredient_2: 'Oil', ingredient_3: 'Cacao',  },
  { id: '27', name: 'Wigglytuff', berry: 'Pecha', ingredient_1: 'Honey', ingredient_2: 'Oil', ingredient_3: 'Cacao',  },
  { id: '28', name: 'Diglett', berry: 'Figy', ingredient_1: 'Tomato', ingredient_2: 'Leek', ingredient_3: 'Soybeans',  },
  { id: '29', name: 'Dugtrio', berry: 'Figy', ingredient_1: 'Tomato', ingredient_2: 'Leek', ingredient_3: 'Soybeans',  },
  { id: '30', name: 'Meowth', berry: 'Persim', ingredient_1: 'Milk', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '31', name: 'Persian', berry: 'Persim', ingredient_1: 'Milk', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '32', name: 'Psyduck', berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Apple', ingredient_3: 'Sausage',  },
  { id: '33', name: 'Golduck', berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Apple', ingredient_3: 'Sausage',  },
  { id: '34', name: 'Mankey', berry: 'Cheri', ingredient_1: 'Sausage', ingredient_2: 'Mushroom', ingredient_3: 'Honey',  },
  { id: '35', name: 'Primeape', berry: 'Cheri', ingredient_1: 'Sausage', ingredient_2: 'Mushroom', ingredient_3: 'Honey',  },
  { id: '36', name: 'Growlithe', berry: 'Leppa', ingredient_1: 'Herb', ingredient_2: 'Sausage', ingredient_3: 'Milk',  },
  { id: '37', name: 'Arcanine', berry: 'Leppa', ingredient_1: 'Herb', ingredient_2: 'Sausage', ingredient_3: 'Milk',  },
  { id: '38', name: 'Bellsprout', berry: 'Durin', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '39', name: 'Weepinbell', berry: 'Durin', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '40', name: 'Victreebel', berry: 'Durin', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '41', name: 'Geodude', berry: 'Sitrus', ingredient_1: 'Soybeans', ingredient_2: 'Potato', ingredient_3: 'Mushroom',  },
  { id: '42', name: 'Graveler', berry: 'Sitrus', ingredient_1: 'Soybeans', ingredient_2: 'Potato', ingredient_3: 'Mushroom',  },
  { id: '43', name: 'Golem', berry: 'Sitrus', ingredient_1: 'Soybeans', ingredient_2: 'Potato', ingredient_3: 'Mushroom',  },
  { id: '44', name: 'Slowpoke', berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Tail', ingredient_3: 'Tomato',  },
  { id: '45', name: 'Slowbro', berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Tail', ingredient_3: 'Tomato',  },
  { id: '46', name: 'Slowking', berry: 'Oran', ingredient_1: 'Cacao', ingredient_2: 'Tail', ingredient_3: 'Tomato',  },
  { id: '47', name: 'Magnemite', berry: 'Belue', ingredient_1: 'Oil', ingredient_2: 'Herb', ingredient_3: '',  },
  { id: '48', name: 'Magneton', berry: 'Belue', ingredient_1: 'Oil', ingredient_2: 'Herb', ingredient_3: '',  },
  { id: '49', name: 'Magnezone', berry: 'Belue', ingredient_1: 'Oil', ingredient_2: 'Herb', ingredient_3: '',  },
  { id: '50', name: 'Doduo', berry: 'Pamtre', ingredient_1: 'Soybeans', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '51', name: 'Dodrio', berry: 'Pamtre', ingredient_1: 'Soybeans', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '52', name: 'Gastly', berry: 'Bluk', ingredient_1: 'Herb', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '53', name: 'Haunter', berry: 'Bluk', ingredient_1: 'Herb', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '54', name: 'Gengar', berry: 'Bluk', ingredient_1: 'Herb', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '55', name: 'Onix', berry: 'Sitrus', ingredient_1: 'Tomato', ingredient_2: 'Sausage', ingredient_3: 'Potato',  },
  { id: '56', name: 'Steelix', berry: 'Belue', ingredient_1: 'Tomato', ingredient_2: 'Sausage', ingredient_3: 'Potato',  },
  { id: '57', name: 'Cubone', berry: 'Figy', ingredient_1: 'Ginger', ingredient_2: 'Cacao', ingredient_3: '',  },
  { id: '58', name: 'Marowak', berry: 'Figy', ingredient_1: 'Ginger', ingredient_2: 'Cacao', ingredient_3: '',  },
  { id: '59', name: 'Kangaskhan', berry: 'Persim', ingredient_1: 'Ginger', ingredient_2: 'Potato', ingredient_3: 'Soybeans',  },
  { id: '60', name: 'Mime Jr.', berry: 'Mago', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '61', name: 'Mr. Mime', berry: 'Mago', ingredient_1: 'Tomato', ingredient_2: 'Potato', ingredient_3: 'Leek',  },
  { id: '62', name: 'Pinsir', berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Apple', ingredient_3: 'Sausage',  },
  { id: '63', name: 'Ditto', berry: 'Persim', ingredient_1: 'Oil', ingredient_2: 'Leek', ingredient_3: 'Tail',  },
  { id: '64', name: 'Eevee', berry: 'Persim', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '65', name: 'Vaporeon', berry: 'Oran', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '66', name: 'Jolteon', berry: 'Grepa', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '67', name: 'Flareon', berry: 'Leppa', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '68', name: 'Espeon', berry: 'Mago', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '69', name: 'Umbreon', berry: 'Wiki', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '70', name: 'Leafeon', berry: 'Durin', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '71', name: 'Glaceon', berry: 'Rawst', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '72', name: 'Sylveon', berry: 'Pecha', ingredient_1: 'Milk', ingredient_2: 'Cacao', ingredient_3: 'Sausage',  },
  { id: '73', name: 'Dratini', berry: 'Yache', ingredient_1: 'Herb', ingredient_2: 'Corn', ingredient_3: 'Oil',  },
  { id: '74', name: 'Dragonair', berry: 'Yache', ingredient_1: 'Herb', ingredient_2: 'Corn', ingredient_3: 'Oil',  },
  { id: '75', name: 'Dragonite', berry: 'Yache', ingredient_1: 'Herb', ingredient_2: 'Corn', ingredient_3: 'Oil',  },
  { id: '76', name: 'Chikorita', berry: 'Durin', ingredient_1: 'Cacao', ingredient_2: 'Honey', ingredient_3: 'Leek',  },
  { id: '77', name: 'Bayleef', berry: 'Durin', ingredient_1: 'Cacao', ingredient_2: 'Honey', ingredient_3: 'Leek',  },
  { id: '78', name: 'Meganium', berry: 'Durin', ingredient_1: 'Cacao', ingredient_2: 'Honey', ingredient_3: 'Leek',  },
  { id: '79', name: 'Cyndaquil', berry: 'Leppa', ingredient_1: 'Ginger', ingredient_2: 'Herb', ingredient_3: 'Oil',  },
  { id: '80', name: 'Quilava', berry: 'Leppa', ingredient_1: 'Ginger', ingredient_2: 'Herb', ingredient_3: 'Oil',  },
  { id: '81', name: 'Typhlosion', berry: 'Leppa', ingredient_1: 'Ginger', ingredient_2: 'Herb', ingredient_3: 'Oil',  },
  { id: '82', name: 'Totodile', berry: 'Oran', ingredient_1: 'Sausage', ingredient_2: 'Oil', ingredient_3: '',  },
  { id: '83', name: 'Croconaw', berry: 'Oran', ingredient_1: 'Sausage', ingredient_2: 'Oil', ingredient_3: '',  },
  { id: '84', name: 'Feraligatr', berry: 'Oran', ingredient_1: 'Sausage', ingredient_2: 'Oil', ingredient_3: '',  },
  { id: '85', name: 'Togepi', berry: 'Pecha', ingredient_1: 'Egg', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '86', name: 'Togetic', berry: 'Pecha', ingredient_1: 'Egg', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '87', name: 'Togekiss', berry: 'Pecha', ingredient_1: 'Egg', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '88', name: 'Mareep', berry: 'Grepa', ingredient_1: 'Herb', ingredient_2: 'Egg', ingredient_3: '',  },
  { id: '89', name: 'Flaaffy', berry: 'Grepa', ingredient_1: 'Herb', ingredient_2: 'Egg', ingredient_3: '',  },
  { id: '90', name: 'Ampharos', berry: 'Grepa', ingredient_1: 'Herb', ingredient_2: 'Egg', ingredient_3: '',  },
  { id: '91', name: 'Bonsly', berry: 'Sitrus', ingredient_1: 'Tomato', ingredient_2: 'Soybeans', ingredient_3: 'Mushroom',  },
  { id: '92', name: 'Sudowoodo', berry: 'Sitrus', ingredient_1: 'Tomato', ingredient_2: 'Soybeans', ingredient_3: 'Mushroom',  },
  { id: '93', name: 'Wooper', berry: 'Oran', ingredient_1: 'Mushroom', ingredient_2: 'Potato', ingredient_3: 'Sausage',  },
  { id: '94', name: 'Quagsire', berry: 'Oran', ingredient_1: 'Mushroom', ingredient_2: 'Potato', ingredient_3: 'Sausage',  },
  { id: '95', name: 'Wynaut', berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '96', name: 'Wobbuffet', berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Mushroom', ingredient_3: 'Oil',  },
  { id: '97', name: 'Heracross', berry: 'Lum', ingredient_1: 'Honey', ingredient_2: 'Mushroom', ingredient_3: 'Sausage',  },
  { id: '98', name: 'Delibird', berry: 'Pamtre', ingredient_1: 'Egg', ingredient_2: 'Apple', ingredient_3: 'Cacao',  },
  { id: '99', name: 'Houndour', berry: 'Wiki', ingredient_1: 'Herb', ingredient_2: 'Ginger', ingredient_3: 'Leek',  },
  { id: '100', name: 'Houndoom', berry: 'Wiki', ingredient_1: 'Herb', ingredient_2: 'Ginger', ingredient_3: 'Leek',  },
  { id: '101', name: 'Raiku', berry: 'Grepa', ingredient_1: 'Sausage', ingredient_2: 'Herb', ingredient_3: 'Leek',  },
  { id: '102', name: 'Entei', berry: 'Leppa', ingredient_1: 'Oil', ingredient_2: 'Tomato', ingredient_3: 'Mushroom',  },
  { id: '103', name: 'Suicune', berry: 'Oran', ingredient_1: 'Apple', ingredient_2: 'Oil', ingredient_3: 'Corn',  },
  { id: '104', name: 'Larvitar', berry: 'Sitrus', ingredient_1: 'Ginger', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '105', name: 'Pupitar', berry: 'Sitrus', ingredient_1: 'Ginger', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '106', name: 'Tyranitar', berry: 'Wiki', ingredient_1: 'Ginger', ingredient_2: 'Soybeans', ingredient_3: 'Sausage',  },
  { id: '107', name: 'Ralts', berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '108', name: 'Kirlia', berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '109', name: 'Gardevoir', berry: 'Mago', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '110', name: 'Gallade', berry: 'Cheri', ingredient_1: 'Apple', ingredient_2: 'Corn', ingredient_3: 'Leek',  },
  { id: '111', name: 'Slakoth', berry: 'Persim', ingredient_1: 'Tomato', ingredient_2: 'Honey', ingredient_3: 'Apple',  },
  { id: '112', name: 'Vigoroth', berry: 'Persim', ingredient_1: 'Tomato', ingredient_2: 'Honey', ingredient_3: 'Apple',  },
  { id: '113', name: 'Slaking', berry: 'Persim', ingredient_1: 'Tomato', ingredient_2: 'Honey', ingredient_3: 'Apple',  },
  { id: '114', name: 'Sableye', berry: 'Wiki', ingredient_1: 'Oil', ingredient_2: 'Mushroom', ingredient_3: 'Cacao',  },
  { id: '115', name: 'Gulpin', berry: 'Chesto', ingredient_1: 'Soybeans', ingredient_2: 'Mushoom', ingredient_3: 'Honey',  },
  { id: '116', name: 'Swalot', berry: 'Chesto', ingredient_1: 'Soybeans', ingredient_2: 'Mushoom', ingredient_3: 'Honey',  },
  { id: '117', name: 'Swablu', berry: 'Pamtre', ingredient_1: 'Egg', ingredient_2: 'Soybeans', ingredient_3: 'Apple',  },
  { id: '118', name: 'Altaria', berry: 'Yache', ingredient_1: 'Egg', ingredient_2: 'Soybeans', ingredient_3: 'Apple',  },
  { id: '119', name: 'Shuppet', berry: 'Bluk', ingredient_1: 'Oil', ingredient_2: 'Ginger', ingredient_3: 'Mushroom',  },
  { id: '120', name: 'Banette', berry: 'Bluk', ingredient_1: 'Oil', ingredient_2: 'Ginger', ingredient_3: 'Mushroom',  },
  { id: '121', name: 'Absol', berry: 'Wiki', ingredient_1: 'Cacao', ingredient_2: 'Apple', ingredient_3: 'Mushroom',  },
  { id: '122', name: 'Spheal', berry: 'Rawst', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: 'Ginger',  },
  { id: '123', name: 'Sealeo', berry: 'Rawst', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: 'Ginger',  },
  { id: '124', name: 'Walrein', berry: 'Rawst', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: 'Ginger',  },
  { id: '125', name: 'Riolu', berry: 'Cheri', ingredient_1: 'Oil', ingredient_2: 'Potato', ingredient_3: 'Egg',  },
  { id: '126', name: 'Lucario', berry: 'Cheri', ingredient_1: 'Oil', ingredient_2: 'Potato', ingredient_3: 'Egg',  },
  { id: '127', name: 'Croagunk', berry: 'Chesto', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '128', name: 'Toxicroak', berry: 'Chesto', ingredient_1: 'Oil', ingredient_2: 'Sausage', ingredient_3: '',  },
  { id: '129', name: 'Snover', berry: 'Rawst', ingredient_1: 'Tomato', ingredient_2: 'Egg', ingredient_3: 'Mushroom',  },
  { id: '130', name: 'Abomasnow', berry: 'Rawst', ingredient_1: 'Tomato', ingredient_2: 'Egg', ingredient_3: 'Mushroom',  },
  { id: '131', name: 'Dedenne', berry: 'Grepa', ingredient_1: 'Apple', ingredient_2: 'Cacao', ingredient_3: 'Corn',  },
  { id: '132', name: 'Stufful', berry: 'Cheri', ingredient_1: 'Corn', ingredient_2: 'Sausage', ingredient_3: 'Egg',  },
  { id: '133', name: 'Bewear', berry: 'Cheri', ingredient_1: 'Corn', ingredient_2: 'Sausage', ingredient_3: 'Egg',  },
  { id: '134', name: 'Comfey', berry: 'Pecha', ingredient_1: 'Corn', ingredient_2: 'Ginger', ingredient_3: 'Cacao',  },
  { id: '135', name: 'Cramorant', berry: 'Pamtre', ingredient_1: 'Oil', ingredient_2: 'Potato', ingredient_3: 'Egg',  },
  { id: '136', name: 'Sprigatito', berry: 'Durin', ingredient_1: 'Potato', ingredient_2: 'Milk', ingredient_3: 'Ginger',  },
  { id: '137', name: 'Floragato', berry: 'Durin', ingredient_1: 'Potato', ingredient_2: 'Milk', ingredient_3: 'Ginger',  },
  { id: '138', name: 'Meowscarada', berry: 'Wiki', ingredient_1: 'Potato', ingredient_2: 'Milk', ingredient_3: 'Ginger',  },
  { id: '139', name: 'Fuecoco', berry: 'Leppa', ingredient_1: 'Apple', ingredient_2: 'Sausage', ingredient_3: 'Herb',  },
  { id: '140', name: 'Crocalor', berry: 'Leppa', ingredient_1: 'Apple', ingredient_2: 'Sausage', ingredient_3: 'Herb',  },
  { id: '141', name: 'Skeledirge', berry: 'Bluk', ingredient_1: 'Apple', ingredient_2: 'Sausage', ingredient_3: 'Herb',  },
  { id: '142', name: 'Quaxly', berry: 'Oran', ingredient_1: 'Soybeans', ingredient_2: 'Leek', ingredient_3: 'Oil',  },
  { id: '143', name: 'Quaxwell', berry: 'Oran', ingredient_1: 'Soybeans', ingredient_2: 'Leek', ingredient_3: 'Oil',  },
  { id: '144', name: 'Quaquaval', berry: 'Cheri', ingredient_1: 'Soybeans', ingredient_2: 'Leek', ingredient_3: 'Oil',  },
]

export type BerryTypes = {
  index: string,
  berryName: string,
  berryImageUri: string,
  typeName: string,
  typeImageUri: string,
}

export const berryTypes : BerryTypes[] = [
  { index: '1', berryName: "Persim", typeName: "Normal", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '2', berryName: "Leppa", typeName: "Fire", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '3', berryName: "Oran", typeName: "Water", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '4', berryName: "Grepa", typeName: "Electric", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '5', berryName: "Durin", typeName: "Grass", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '6', berryName: "Rawst", typeName: "Ice", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '7', berryName: "Cheri", typeName: "Fighting", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '8', berryName: "Chesto", typeName: "Poison", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '9', berryName: "Figy", typeName: "Ground", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '10', berryName: "Pamtre", typeName: "Flying", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '11', berryName: "Mago", typeName: "Psychic", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '12', berryName: "Lum", typeName: "Bug", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '13', berryName: "Sitrus", typeName: "Rock", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '14', berryName: "Bluk", typeName: "Ghost", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '15', berryName: "Yache", typeName: "Dragon", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '16', berryName: "Wiki", typeName: "Dark", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '17', berryName: "Belue", typeName: "Steel", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
  { index: '18', berryName: "Pecha", typeName: "Fairy", berryImageUri: "./portraits/001.png", typeImageUri: "./portraits/002.png" },
]

export type Recipe = {
  key: string,
  Type: string,
  Dish: string,
  Apple: string,
  Honey: string,
  Milk: string,
  Ginger: string,
  Oil: string,
  Cacao: string,
  Egg: string,
  Soybeans: string,
  Potato: string,
  Tomato: string,
  Mushroom: string,
  Tail: string,
  Herb: string,
  Leek: string,
  Corn: string,
  Sausage: string,
  Total_ingredients: string,
}

export type Ingredients = {
  Apple: string,
  Honey: string,
  Milk: string,
  Ginger: string,
  Oil: string,
  Cacao: string,
  Egg: string,
  Soybeans: string,
  Potato: string,
  Tomato: string,
  Mushroom: string,
  Tail: string,
  Herb: string,
  Leek: string,
  Corn: string,
  Sausage: string,
}

export const ingredients = [
  "Apple",
  "Honey",
  "Milk",
  "Ginger",
  "Oil",
  "Cacao",
  "Egg",
  "Soybeans",
  "Potato",
  "Tomato",
  "Mushroom",
  "Tail",
  "Herb",
  "Leek",
  "Corn",
  "Sausage",
]

export const recipes : Recipe[] = [
  { key: '0', Type: "Curry", Dish: "Fancy Apple Curry", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '1', Type: "Curry", Dish: "Simple Chowder", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '2', Type: "Curry", Dish: "Beanburger Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "7",  },
  { key: '3', Type: "Curry", Dish: "Mild Honey Curry", Apple: "0", Honey: "7", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '4', Type: "Curry", Dish: "Solar Power Tomato Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "10", Mushroom: "0", Tail: "0", Herb: "5", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '5', Type: "Curry", Dish: "Drought Katsu Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "10", Total_ingredients: "15",  },
  { key: '6', Type: "Curry", Dish: "Hearty Cheeseburger Curry", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "16",  },
  { key: '7', Type: "Curry", Dish: "Melty Omelette Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "10", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '8', Type: "Curry", Dish: "Soft Potato Chowder", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "4", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '9', Type: "Curry", Dish: "Spore Mushroom Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "14", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '10', Type: "Curry", Dish: "Bulk Up Bean Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "4", Soybeans: "12", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "4", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "26",  },
  { key: '11', Type: "Curry", Dish: "Limber Corn Stew", Apple: "0", Honey: "0", Milk: "8", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "8", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "14", Sausage: "0", Total_ingredients: "30",  },
  { key: '12', Type: "Curry", Dish: "Spicy Leek Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "8", Leek: "14", Corn: "0", Sausage: "0", Total_ingredients: "32",  },
  { key: '13', Type: "Curry", Dish: "Grilled Tail Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "8", Herb: "25", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '14', Type: "Curry", Dish: "Egg Bomb Curry", Apple: "11", Honey: "12", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "0", Potato: "4", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '15', Type: "Curry", Dish: "Ninja Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "24", Potato: "0", Tomato: "0", Mushroom: "5", Tail: "0", Herb: "0", Leek: "12", Corn: "0", Sausage: "9", Total_ingredients: "50",  },
  { key: '16', Type: "Curry", Dish: "Dream Eater Butter Curry", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "12", Egg: "0", Soybeans: "0", Potato: "18", Tomato: "15", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '17', Type: "Curry", Dish: "Inferno Corn Keema Curry", Apple: "0", Honey: "0", Milk: "0", Ginger: "12", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "27", Leek: "0", Corn: "14", Sausage: "24", Total_ingredients: "77",  },
  { key: '18', Type: "Salad", Dish: "Bean Ham Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "8", Total_ingredients: "8",  },
  { key: '19', Type: "Salad", Dish: "Snoozy Tomato Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '20', Type: "Salad", Dish: "Fancy Apple Salad", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '21', Type: "Salad", Dish: "Immunity Leek Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "5", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "10", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '22', Type: "Salad", Dish: "Snow Cloak Caesar Salad", Apple: "0", Honey: "0", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "6", Total_ingredients: "16",  },
  { key: '23', Type: "Salad", Dish: "Water Veil Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '24', Type: "Salad", Dish: "Heat Wave Tofu Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "10", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "6", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '25', Type: "Salad", Dish: "Fury Attack Corn Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "9", Sausage: "0", Total_ingredients: "17",  },
  { key: '26', Type: "Salad", Dish: "Superpower Extreme Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "6", Oil: "0", Cacao: "0", Egg: "5", Soybeans: "0", Potato: "3", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '27', Type: "Salad", Dish: "Moomoo Caprese Salad", Apple: "0", Honey: "0", Milk: "12", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "6", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '28', Type: "Salad", Dish: "Contrary Chocolate Meat Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "14", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "9", Total_ingredients: "23",  },
  { key: '29', Type: "Salad", Dish: "Dazzling Apple Cheese Salad", Apple: "15", Honey: "0", Milk: "5", Ginger: "0", Oil: "3", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '30', Type: "Salad", Dish: "Slowpoke Tail Pepper Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "5", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "10", Herb: "10", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "25",  },
  { key: '31', Type: "Salad", Dish: "Spore Mushroom Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "8", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "17", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "33",  },
  { key: '32', Type: "Salad", Dish: "Overheat Ginger Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "10", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "8", Mushroom: "0", Tail: "0", Herb: "17", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '33', Type: "Salad", Dish: "Gluttony Potato Salad", Apple: "6", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "9", Soybeans: "0", Potato: "14", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "7", Total_ingredients: "36",  },
  { key: '34', Type: "Salad", Dish: "Calm Mind Fruit Salad", Apple: "21", Honey: "16", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "12", Sausage: "0", Total_ingredients: "49",  },
  { key: '35', Type: "Salad", Dish: "Ninja Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "19", Potato: "0", Tomato: "0", Mushroom: "12", Tail: "0", Herb: "0", Leek: "15", Corn: "0", Sausage: "0", Total_ingredients: "57",  },
  { key: '36', Type: "Salad", Dish: "Greengrass Salad", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "22", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "14", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "17", Sausage: "0", Total_ingredients: "62",  },
  { key: '37', Type: "Dessert", Dish: "Warm Moomoo Milk", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "7",  },
  { key: '38', Type: "Dessert", Dish: "Fancy Apple Juice", Apple: "8", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "8",  },
  { key: '39', Type: "Dessert", Dish: "Craft Soda Pop", Apple: "0", Honey: "9", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "9",  },
  { key: '40', Type: "Dessert", Dish: "Fluffy Sweet Potatoes", Apple: "0", Honey: "0", Milk: "5", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "9", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "14",  },
  { key: '41', Type: "Dessert", Dish: "Cloud Nine Soy Cake", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "8", Soybeans: "7", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "15",  },
  { key: '42', Type: "Dessert", Dish: "Ember Ginger Tea", Apple: "7", Honey: "0", Milk: "0", Ginger: "9", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '43', Type: "Dessert", Dish: "Lucky Chant Apple Pie", Apple: "12", Honey: "0", Milk: "4", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '44', Type: "Dessert", Dish: "Stalwart Vegetable Juice", Apple: "7", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "9", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "16",  },
  { key: '45', Type: "Dessert", Dish: "Huge Power Soy Donuts", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "12", Cacao: "7", Egg: "0", Soybeans: "16", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '46', Type: "Dessert", Dish: "Petal Dance Chocolate Tart", Apple: "11", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "11", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "22",  },
  { key: '47', Type: "Dessert", Dish: "Hustle Protein Smoothie", Apple: "0", Honey: "0", Milk: "0", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "15", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '48', Type: "Dessert", Dish: "Big Malasada", Apple: "0", Honey: "6", Milk: "7", Ginger: "0", Oil: "10", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "23",  },
  { key: '49', Type: "Dessert", Dish: "Sweet Scent Chocolate Cake", Apple: "0", Honey: "9", Milk: "7", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "24",  },
  { key: '50', Type: "Dessert", Dish: "Steadfast Ginger Cookies", Apple: "0", Honey: "14", Milk: "0", Ginger: "12", Oil: "0", Cacao: "5", Egg: "4", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '51', Type: "Dessert", Dish: "Lovely Kiss Smoothie", Apple: "11", Honey: "7", Milk: "9", Ginger: "0", Oil: "0", Cacao: "8", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '52', Type: "Dessert", Dish: "Neroli's Restorative Tea", Apple: "15", Honey: "0", Milk: "0", Ginger: "11", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "9", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "35",  },
  { key: '53', Type: "Dessert", Dish: "Explosion Popcorn", Apple: "0", Honey: "0", Milk: "7", Ginger: "0", Oil: "14", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "15", Sausage: "0", Total_ingredients: "36",  },
  { key: '54', Type: "Dessert", Dish: "Jigglypuff's Fruity Flan", Apple: "10", Honey: "20", Milk: "10", Ginger: "0", Oil: "0", Cacao: "0", Egg: "15", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "55",  },
  { key: '55', Type: "Dessert", Dish: "Teatime Corn Scones", Apple: "20", Honey: "0", Milk: "9", Ginger: "20", Oil: "0", Cacao: "0", Egg: "0", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "18", Sausage: "0", Total_ingredients: "67",  },
  { key: '56', Type: "Dessert", Dish: "Flower Gift Macarons", Apple: "0", Honey: "17", Milk: "10", Ginger: "0", Oil: "0", Cacao: "25", Egg: "25", Soybeans: "0", Potato: "0", Tomato: "0", Mushroom: "0", Tail: "0", Herb: "0", Leek: "0", Corn: "0", Sausage: "0", Total_ingredients: "77",  },
]